### PR TITLE
Fix `AWS_REGION` and `AWS_DEFAULT_REGION` support for eksctl commands

### LINKED ISSUE #6774: [Bug] AWS_REGION and AWS_DEFAULT_REGION support broken for `eksctl` commands
### What were you trying to accomplish?
eksctl should support AWS_REGION and AWS_DEFAULT_REGION environment variables

### What happened?
After updating to 0.148.0 setting AWS_REGION via environment variables doesn't work anymore and just RegionUSWest2 is used

### How to reproduce it?
```
1. AWS_DEFAULT_REGION=eu-central-1 eksctl utils write-kubeconfig --cluster $CLUSTERNAME --kubeconfig=test // broken
2. AWS_REGION=eu-central-1 eksctl utils write-kubeconfig --cluster$CLUSTERNAME --kubeconfig=test // broken
3. eksctl utils write-kubeconfig --region eu-central-1 --cluster$CLUSTERNAME --kubeconfig=test // working
```
**Logs**
```
1. Error: unable to describe cluster control plane: operation error EKS: DescribeCluster, https response error StatusCode: 404, RequestID: 4d81a24f-dc40-4d1d-9718-f5ced4ed3ca4, ResourceNotFoundException: No cluster found for name: $CLUSTERNAME
2. Error: unable to describe cluster control plane: operation error EKS: DescribeCluster, https response error StatusCode: 404, RequestID: 6cbcdc97-2f9c-4ca1-8294-bf749421c34f, ResourceNotFoundException: No cluster found for name: $CLUSTERNAME
3. 2023-07-07 17:01:46 [✔]  saved kubeconfig as "test"
```

**Anything else we need to know?**
Caused by: https://github.com/weaveworks/eksctl/pull/6747

Maybe? https://github.com/weaveworks/eksctl/commit/38d294b75fb84aa3f605e2116b0a0363dc92bb18#diff-6cb45ad9f4ca49a198b4b736bee189dccb0e862901d5fad102cdd5c69023e7f0R35

**Versions**
```
$ eksctl info
eksctl version: 0.148.0
kubectl version: v1.27.3
OS: darwin
```

### PR DESCRIPTION
**Pull request by TiberiuGC**
### Description

After migrating to `aws-sdk-go-v2`, the following regression was introduced: if region wasn't user provided as part of config file / CLI,  we stopped fetching it from config resolver. This PR aims to bring the functionality back.

Closes #6774

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by cPu1 — APPROVED** [review]

**Comment by Himangini** [comment]
Question: Is there a chance we can add tests for this?

**Comment by TiberiuGC** [comment]
> Question: Is there a chance we can add tests for this?

We absolutely sound. I'll open a separate ticket for it.

**Comment by Himangini** [comment]
> > Question: Is there a chance we can add tests for this?
> 
> We absolutely should. I'll open a separate ticket for it.

Why not add here? 🤔

**Comment by TiberiuGC** [comment]
> Why not add here? 🤔

May need some refactoring and/or new mocks.

**Comment by Himangini** [comment]
> > Why not add here? 🤔
> 
> May need some refactoring and/or new mocks.

thanks, adding a new ticket sounds good 👍🏻

**Pull request merged**
