### PR TITLE
Remove k8s.io/kubernetes dependency by using k8s.io/kubelet

### PR DESCRIPTION
**Pull request by aledbf**
### Description

Remove direct dependency `k8s.io/kubernetes` dependency by using [k8s.io/kubelet](https://github.com/kubernetes/kubelet)

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [X] Manually tested
- [X] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Callisto13** [comment]
Thanks for the PR @aledbf !

There are a couple of tests failing, could you please run `make test`?

**Comment by Callisto13** [comment]
Ah that new docker image will need to be pushed to our account, I'll take care of that 👍

**Comment by Callisto13** [comment]
A couple of tests in `pkg/utils/kubeconfig/kubeconfig_test.go` still failing 😄

**Comment by aledbf** [comment]
@Callisto13 apologies for the delay. The tests are passing now.

**Review by Callisto13 — APPROVED** [review]
LGTM, thanks 🚀 

Good to merge once the conflicts are resolved 👍 

Edit: actually I think the resolution will involve another image build/push, so I can do this

Edit 2: I am not able to push to your branch (did you uncheck the box which allows edits by maintainers?), so once you have resolved the conflicts I can push the new image 👍

**Comment by aledbf** [comment]
@Callisto13 rebased

**Comment by aledbf** [comment]
> Edit 2: I am not able to push to your branch (did you uncheck the box which allows edits by maintainers?), so once you have resolved the conflicts I can push the new image

Not, it's checked.

**Comment by Callisto13** [comment]
> Not, it's checked.

Huh weird 🤔

**Comment by Callisto13** [comment]
For some reason I am not able to push to your branch, could you run `make check-build-image-manifest-up-to-date` and commit the result?

**Pull request merged**
