### PR TITLE
Add AZ selector logic

### LINKED ISSUE #118: UnsupportedAvailabilityZoneException: lack of capacity to support cluster
unable to create cluster control plane: UnsupportedAvailabilityZoneException: Cannot create cluster '****-**' because us-east-1c, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1d

### PR DESCRIPTION
**Pull request by errordeveloper**
Fixes #118 and #101.

### CODE REVIEW

**Comment by errordeveloper** [comment]
We have test and they are failing, isn't that nice? 😺

**Comment by errordeveloper** [comment]
@richardcase tests LGTM, thanks you!

**Comment by richardcase** [comment]
When trying to create a cluster with this i get the following error:
```
2018-07-19T14:17:38+01:00 [✖]  creating CloudFormation stack "EKS-richtest23-VPC": ValidationError: Parameters: [AvailabilityZones] do not exist in the template
        status code: 400, request id: 1b9221c4-8b56-11e8-88ec-dfaeea4eb12a
```

Looking at the debug output i can see the availability zones are passed in as a parameter but i don't think they are mapped into the template:
```
2018-07-19T14:17:37+01:00 [▶]  input = {
  Parameters: [{
      ParameterKey: "AvailabilityZones",
      ParameterValue: "us-west-2a,us-west-2c,us-west-2b"
    }],
  StackName: "EKS-richtest23-VPC",
  Tags: [{
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "richtest23"
    }],
  TemplateBody: "---\nAWSTemplateFormatVersion: '2010-09-09'\nDescription: 'Amazon EKS Sample VPC'\n\nParameters:\n\n  VpcBlock:\n    Type: String\n    Default: 192.168.0.0/16\n    Description: The CIDR range for the VPC. This should be a valid private (RFC 1918) CIDR range.\n\n  Subnet01Block:\n    Type: String\n    Default: 192.168.64.0/18\n    Description: CidrBlock for subnet 01 within the VPC\n\n  Subnet02Block:\n    Type: String\n    Default: 192.168.128.0/18\n    Description: CidrBlock for subnet 02 within the VPC\n\n  Subnet03Block:\n    Type: String\n    Default: 192.168.192.0/18\n    Description: CidrBlock for subnet 03 within the VPC\n\nMetadata:\n  AWS::CloudFormation::Interface:\n    ParameterGroups:\n      -\n        Label:\n          default: \"Worker Network Configuration\"\n        Parameters:\n          - VpcBlock\n          - Subnet01Block\n          - Subnet02Block\n          - Subnet03Block\n\nResources:\n  VPC:\n    Type: AWS::EC2::VPC\n    Properties:\n      CidrBlock:  !Ref VpcBlock\n      EnableDnsSupport: true\n      EnableDnsHostnames: true\n      Tags:\n      - Key: Name\n        Value: !Sub '${AWS::StackName}-VPC'\n\n  InternetGateway:\n    Type: \"AWS::EC2::InternetGateway\"\n\n  VPCGatewayAttachment:\n    Type: \"AWS::EC2::VPCGatewayAttachment\"\n    Properties:\n      InternetGatewayId: !Ref InternetGateway\n      VpcId: !Ref VPC\n\n  RouteTable:\n    Type: AWS::EC2::RouteTable\n    Properties:\n      VpcId: !Ref VPC\n      Tags:\n      - Key: Name\n        Value: Public Subnets\n      - Key: Network\n        Value: Public\n\n  Route:\n    DependsOn: VPCGatewayAttachment\n    Type: AWS::EC2::Route\n    Properties:\n      RouteTableId: !Ref RouteTable\n      DestinationCidrBlock: 0.0.0.0/0\n      GatewayId: !Ref InternetGateway\n\n  Subnet01:\n    Type: AWS::EC2::Subnet\n    Metadata:\n      Comment: Subnet 01\n    Properties:\n      AvailabilityZone:\n        Fn::Select:\n        - '0'\n        - Fn::GetAZs:\n            Ref: AWS::Region\n      CidrBlock:\n        Ref: Subnet01Block\n      VpcId:\n        Ref: VPC\n      Tags:\n      - Key: Name\n        Value: !Sub \"${AWS::StackName}-Subnet01\"\n\n  Subnet02:\n    Type: AWS::EC2::Subnet\n    Metadata:\n      Comment: Subnet 02\n    Properties:\n      AvailabilityZone:\n        Fn::Select:\n        - '1'\n        - Fn::GetAZs:\n            Ref: AWS::Region\n      CidrBlock:\n        Ref: Subnet02Block\n      VpcId:\n        Ref: VPC\n      Tags:\n      - Key: Name\n        Value: !Sub \"${AWS::StackName}-Subnet02\"\n\n  Subnet03:\n    Type: AWS::EC2::Subnet\n    Metadata:\n      Comment: Subnet 03\n    Properties:\n      AvailabilityZone:\n        Fn::Select:\n        - '2'\n        - Fn::GetAZs:\n            Ref: AWS::Region\n      CidrBlock:\n        Ref: Subnet03Block\n      VpcId:\n        Ref: VPC\n      Tags:\n      - Key: Name\n        Value: !Sub \"${AWS::StackName}-Subnet03\"\n\n  Subnet01RouteTableAssociation:\n    Type: AWS::EC2::SubnetRouteTableAssociation\n    Properties:\n      SubnetId: !Ref Subnet01\n      RouteTableId: !Ref RouteTable\n\n  Subnet02RouteTableAssociation:\n    Type: AWS::EC2::SubnetRouteTableAssociation\n    Properties:\n      SubnetId: !Ref Subnet02\n      RouteTableId: !Ref RouteTable\n\n  Subnet03RouteTableAssociation:\n    Type: AWS::EC2::SubnetRouteTableAssociation\n    Properties:\n      SubnetId: !Ref Subnet03\n      RouteTableId: !Ref RouteTable\n\n  ControlPlaneSecurityGroup:\n    Type: AWS::EC2::SecurityGroup\n    Properties:\n      GroupDescription: Cluster communication with worker nodes\n      VpcId: !Ref VPC\n\nOutputs:\n\n  SubnetIds:\n    Description: All subnets in the VPC\n    Value: !Join [ \",\", [ !Ref Subnet01, !Ref Subnet02, !Ref Subnet03 ] ]\n\n  SecurityGroups:\n    Description: Security group for the cluster control plane communication with worker nodes\n    Value: !Join [ \",\", [ !Ref ControlPlaneSecurityGroup ] ]\n\n  VpcId:\n    Description: The VPC Id\n    Value: !Ref VPC\n"
}

```

Not sure how i update the template.

**Comment by errordeveloper** [comment]
@richardcase that error was because we forgot to re-genrate biodata for the templates.

**Pull request merged**
