### PR TITLE
fix mockery syntax

### PR DESCRIPTION
**Pull request by chenrui333**
### Description

Quick fix for mockery syntax change.

```
go generate ./pkg/eks
Error: unknown shorthand flag: 'n' in -name=KubeNodeGroup
```

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [ ] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by chenrui333** [comment]
not sure how to label the PRs. :(

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/67439

**Comment by Callisto13** [comment]
Thanks @chenrui333!

Could you also get the ones in `pkg/eks/mocks/mocks.go`?

**Comment by Callisto13** [comment]
@chenrui333 are you still working on this? If not, one of the team can continue the work, it would be good to get this in and bump to v2 😃

**Comment by chenrui333** [comment]
yeah, I can do a quick check. This PR helps unblocking my homebrew one though. 😄

**Comment by chenrui333** [comment]
running `make generate-all` now

**Comment by chenrui333** [comment]
@Callisto13 all set, thanks!

**Review by Callisto13 — APPROVED** [review]
Sweet! LGTM

**Pull request merged**
