### PR TITLE
Fix variable scoping and version check in integration tests

### LINKED ISSUE #900: MissingRegion error in integration tests
```
(Integration) Create, Get, Scale & Delete when creating a cluster with 1 node and deleting the cluster 
  {FLAKY: https://github.com/weaveworks/eksctl/issues/536} should have deleted the EKS cluster
  /home/martina/goprojects/src/github.com/weaveworks/eksctl/integration/creategetdelete_test.go:424

• Failure [0.001 seconds]
(Integration) Create, Get, Scale & Delete
/home/martina/goprojects/src/github.com/weaveworks/eksctl/integration/creategetdelete_test.go:28
  when creating a cluster with 1 node
  /home/martina/goprojects/src/github.com/weaveworks/eksctl/integration/creategetdelete_test.go:54
    and deleting the cluster
    /home/martina/goprojects/src/github.com/weaveworks/eksctl/integration/creategetdelete_test.go:408
      {FLAKY: https://github.com/weaveworks/eksctl/issues/536} should have deleted the EKS cluster [It]
      /home/martina/goprojects/src/github.com/weaveworks/eksctl/integration/creategetdelete_test.go:424

      MissingRegion: could not find region configuration

      /home/martina/goprojects/src/github.com/weaveworks/eksctl/integration/creategetdelete_test.go:429
```

### PR DESCRIPTION
**Pull request by errordeveloper**
### Description

Fix #900 

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [x] All unit tests passing (i.e. `make test`)

### CODE REVIEW

**Comment by errordeveloper** [comment]
I've not verified it just yet, will report back to confirm, but I'm rather certain it'll fix the error.

**Comment by martina-if** [comment]
I tried a similar fix a few mins ago and it works. I still get the flaky tests though. Should we increase the timeout by 10 mins or so? I did that once and it helped

**Comment by errordeveloper** [comment]
> Should we increase the timeout by 10 mins or so? I did that once and it helped

Sure, please open another PR!

**Comment by errordeveloper** [comment]
I'll re-run the test here, as I've managed to clear the terminal output before I looked at it.

**Pull request merged**
