### PR TITLE
Make addon.Force unconfigurable

### PR DESCRIPTION
**Pull request by cPu1**
### Description

`addon.Force` is an internal field but it's still configurable in ClusterConfig. 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by aclevername** [comment]
Is there a reason why we wouldn't want this to be configurable from inside the config file?

**Comment by cPu1** [comment]
> Is there a reason why we wouldn't want this to be configurable from inside the config file?

I believe this field was added for supporting the `--force` flag. If we fully support this field, the UX for `--force` along with `addon.force: false` can be tricky to get right (does `--force` override `addon.force`?). Furthermore, `addon.force` in itself does not convey whether it's for forcing the creation, update or deletion, so if we do want to support this feature, I think it should be named appropriately (`forceCreate` or `forceUpdate`?).

**Comment by aclevername** [comment]
does the current `--force` flag work when a config file is provided?

**Comment by cPu1** [comment]
> does the current `--force` flag work when a config file is provided?

I think so, which is why the current UX can be confusing.

**Review by aclevername — APPROVED** [review]

**Pull request merged**
