### PR TITLE
bump vpc-resource-controller/webhook dep to v0.2.7

### PR DESCRIPTION
**Pull request by abhipth**
### Description
Updating the controller image. 

```
curl --silent https://amazon-eks.s3.us-west-2.amazonaws.com/manifests/us-west-2/vpc-resource-controller/latest/vpc-resource-controller.yaml | grep image:
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/windows-vpc-resource-controller:v0.2.7
curl --silent https://amazon-eks.s3.us-west-2.amazonaws.com/manifests/us-west-2/vpc-admission-webhook/latest/vpc-admission-webhook-deployment.yaml | grep image:
          image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/vpc-admission-webhook:v0.2.7
```

Not able to generate-manifest
```
go: github.com/vartanbeno/go-reddit/v2@v2.0.1: reading github.com/vartanbeno/go-reddit/go.mod at revision v2.0.1: unknown revision v2.0.1
```

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by aclevername** [comment]
> > The release has likely been deleted - https://github.com/vartanbeno/go-reddit/releases/tag/v2.0.1
> > I think If you run `go clean -modcache` and try building you would also run into the same error.
> 
> Huh that is odd! I can still seem to build it even after running `go clean -modcache`, even though as you point out that tag has been deleted, very strange. If you try modifying the `go.mod` to use `v2.0.0` and then run `make install-build-deps` does it work?

Should be fixed in main https://github.com/weaveworks/eksctl/pull/4348

**Comment by abhipth** [comment]
@aclevername it's now failing with,
```
verifying github.com/vartanbeno/go-reddit/v2@v2.0.0: checksum mismatch
	downloaded: h1:vjb+mY2GwC00uKeXdM+efhzEJoScc0oQfP5CZrE2R28=
	go.sum:     h1:fxYMqx5lhbmJ3yYRN1nnQC/gecRB3xpUS2BbG7GLpsk=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

I think I have seen this, if the same tag is re-used.

**Comment by abhipth** [comment]
@aclevername I am running into new issues after pulling in the latest changes, could you please run the command at your end. Thanks

**Comment by cPu1** [comment]
> @aclevername I am running into new issues after pulling in the latest changes, could you please run the command at your end. Thanks

We switched to `go:embed` last week and the process for generating assets has changed.

**Review by cPu1 — APPROVED** [review]

**Pull request merged**
