### PR TITLE
WIP: Added eksctl get supported-regions command

### PR DESCRIPTION
**Pull request by bowlesns**
In response to issue #222, I added a command to allow a user
to get the regions where EKS is currently supported. After
some discussion with another contributor, thought it would
be better under the "get" command.

The command is simple, and prints out a few lines showing
which regions EKS is currently supported in. I also added
the url where the most up to date information is on AWS.

Issue #222

### Description
Please explain the changes you made here.

### Checklist
- [X] Code compiles correctly (i.e `make build`)
- [ ] Added tests that cover your change (if possible)
- [ ] All tests passing (i.e. `make test`)
- [ ] Added/modified documentation as required (such as the README)
- [x] Added yourself to the `humans.txt` file

### CODE REVIEW

**Comment by bowlesns** [comment]
Adding as a WIP. Wanted to ask if it's worth adding in the "printers" functionality that was just added to output multiple formats, or if the command will suffice as-is.

**Comment by richardcase** [comment]
Great, thanks @bowlesns.

I like the idea of having the list of regions outputted as a table. But not sure if its actually needed.

@errordeveloper  - Do you think it would be good if we used the table printer or just leave it using formatted text?

**Comment by redborian** [comment]
@bowlesns Just a thought: Instead of hard-coding the command output, can we get the list of regions from `eksctl/cmd/eksctl/create.go`?

**Comment by errordeveloper** [comment]
Let's refactor the code a little bit and add `[]string` to hold supported regions.

**Comment by richardcase** [comment]
@errordeveloper @bowlesns  - apologies as this was initially under utils and then i thought it flowed better being under `get`. But if by having something under `get` this also implies there should be `delete` and `create` then i was wrong in my advice (sorry @bowlesns)

**Comment by errordeveloper** [comment]
I've happened to add `api.SupportedRegions` [in #273](https://github.com/weaveworks/eksctl/pull/273/files#diff-9c8e1b263f86d71b19e53c9ce3853aa1R30), which we will probably merge pretty soon.

**Comment by errordeveloper** [comment]
Hey @bowlesns I'm gonna have to close this, but feel free to re-open if you want to get back to it!

**Pull request closed without merging**
