### PR TITLE
remove MinInstancesInService and MaxBatchSize fields

### PR DESCRIPTION
**Pull request by aclevername**
### Description

~~⚠️ This goformation PR needs to be merged first and this PR updated with it before merging ⚠️  https://github.com/weaveworks/goformation/pull/7~~

fixes https://github.com/weaveworks/eksctl/issues/3190

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by aclevername** [comment]
tested `eksctl scale` locally and it succeeded 👍

**Comment by aclevername** [comment]
⚠️ putting into draft mode:
```
[✔]  created 1 nodegroup(s) in cluster "jk-cf"
[✔]  created 0 managed nodegroup(s) in cluster "jk-cf"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2431b37]

goroutine 1 [running]:
encoding/json.(*encodeState).marshal.func1(0xc00017f5f8)
        /usr/local/Cellar/go/1.15.5/libexec/src/encoding/json/encode.go:326 +0x85
panic(0x37828a0, 0x58ab810)
        /usr/local/Cellar/go/1.15.5/libexec/src/runtime/panic.go:969 +0x1b9
encoding/json.(*encodeState).marshal.func1(0xc00017ecf0)
        /usr/local/Cellar/go/1.15.5/libexec/src/encoding/json/encode.go:326 +0x85
panic(0x37828a0, 0x58ab810)
        /usr/local/Cellar/go/1.15.5/libexec/src/runtime/panic.go:969 +0x1b9
github.com/weaveworks/goformation/v4/cloudformation/types.Value.MarshalJSON(...)
        /Users/jake/workspace/go/pkg/mod/github.com/weaveworks/goformation/v4@v4.10.2-0.20210202171226-c2d601871472/cloudformation/types/types.go:102
encoding/json.addrMarshalerEncoder(0xc0006d9f80, 0x38b9820, 0xc000739a40, 0x199, 0x100)
        /usr/local/Cellar/go/1.15.5/libexec/src/encoding/json/encode.go:494 +0xe4
encoding/json.condAddrEncoder.encode(0x3f5ad38, 0x3f5ad90, 0xc0006d9f80, 0x38b9820, 0x
```

**Comment by aclevername** [comment]
Fixed in https://github.com/weaveworks/goformation/pull/8

Tested scale and create, both succeeded with this change

**Review by michaelbeaumont — APPROVED** [review]

**Comment by aclevername** [comment]
running the CRUD integration test first before merging

**Review by michaelbeaumont — APPROVED** [review]

**Comment by aclevername** [comment]
```

Ran 39 of 39 Specs in 2880.174 seconds
SUCCESS! -- 39 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestCRUD (2880.18s)
PASS

Ginkgo ran 1 suite in 48m13.549855315s
```

Merging

**Pull request merged**
