### PR TITLE
Document current design of node bootstrap process

### PR DESCRIPTION
**Pull request by errordeveloper**
The purpose of this document is to summaries how node bootstrap process is currently implemented in `eksctl`,  so it can be referred to in any discussions.

### CODE REVIEW

**Comment by whereisaaron** [comment]
This is super awesome @errordeveloper, thank you for writing it. Reads well. This definitely belongs on the website please!

The only content thing I noted it that it doesn't cover or reference how you can customise the kubelet config with the `eksctl` config (e.g. to reserve kubelet resources). It is not clear to me how that works to modify the drop-in files?

I think it is great that the actual script/files are included in the discussion (with links to the particular commit), but wonder if that sets it up to fall our of date later? Kinda not DRY 😄 

Could we integrate this document into the website and employ the static site generator to embed the matching version of the relevant files as the documentation website is generated?

**Comment by errordeveloper** [comment]
> The only content thing I noted it that it doesn't cover or reference how you can customise the kubelet config with the `eksctl` config (e.g. to reserve kubelet resources). It is not clear to me how that works to modify the drop-in files?

Resource reservation is documented here: https://eksctl.io/usage/customizing-the-kubelet/

If you really must have a drop-in for some special case, you will need to add a shell script via `preBootstrapCommands`.

> I think it is great that the actual script/files are included in the discussion (with links to the particular commit), but wonder if that sets it up to fall our of date later?

Well, that's a general issue with documentation, hence this document didn't exist for a while...

> Could we integrate this document into the website and employ the static site generator to embed the matching version of the relevant files as the documentation website is generated?

I suppose we could, I just didn't see this as use-facing kind of documentation, but perhaps I'm wrong on that one. To me this was an implementation detail that need documenting, so new contributors are informed of motivation and goals, as until now was mostly in my head.

**Comment by whereisaaron** [comment]
> Resource reservation is documented here: https://eksctl.io/usage/customizing-the-kubelet/

Yep that is cool, but that document and this one, don’t say how those kubelet configuration values are incorporated for the bootstrap process (that I spotted?).

> I suppose we could, I just didn't see this as use-facing kind of documentation, but perhaps I'm wrong on that one. To me this was an implementation detail that need documenting, so new contributors are informed of motivation and goals, as until now this was mostly in my head.

Well I’d read it 😀 This is a key difference between `eksctl` clusters and ‘standard’ EKS clusters, so it worth mentioning. And if you are ever investigating a node problem, it is helpful to know what goes were. It could be buried in the back or under ‘Advanced Topics’ to be sure.

**Comment by errordeveloper** [comment]
@whereisaaron fair enough, I've opened https://github.com/weaveworks/eksctl/issues/1357.

**Pull request merged**
