### PR TITLE
Ensure GPU AMI is used when using multiple instances

### LINKED ISSUE #3848: Managed nodegroup: Bottlerocket, unsupported arm64
Pre populates amd64 ami even for arm64.
```
 AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI. (Service: AmazonEKS; Status Code: 400; Error Code: InvalidRequestException; Request ID: cf1f2a91-18e7-4301-9941-1e6c393b9f00; Proxy: null)"
```

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Fixes #3848 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by Callisto13 — APPROVED** [review]
👍

**Comment by Callisto13** [comment]
gonna merge now so we can kick of the tests before the release

**Comment by Callisto13** [comment]
oh fek were you waiting for integration tests yourself? 😂

**Comment by cPu1** [comment]
> oh fek were you waiting for integration tests yourself before you merged? sorry!

No worries :smiley:

**Pull request merged**
