### PR TITLE
Add support for Fargate

### PR DESCRIPTION
**Pull request by rndstr**
### Description

- Add flag to cluster creation `eksctl create cluster --fargate` to automatically create Fargate profiles
- Support Fargate profiles in cluster config
- Add commands `eksctl create|get|delete fargateprofile`

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [x] Manually tested

### CODE REVIEW

**Comment by arun-gupta** [comment]
when is `brew upgrade eksctl` getting updated?

**Comment by marccarre** [comment]
@arun-gupta, tomorrow, when the `0.11.0` release happens.
(And as previously discussed & agreed between @gemagomez, Nate Taber, Eswar Bala, et al.)

In the meantime, there is a release candidate available here: [0.11.0-rc.0](https://github.com/weaveworks/eksctl/releases/tag/0.11.0-rc.0).

**Comment by awsimaya** [comment]
`brew upgrade` still doesn't seem to do the update yet.

**Comment by kalbir** [comment]
@awsimaya It is working for me.

Screenshot 2019-12-05 at 12 25 42

**Pull request merged**
