### PR TITLE
Parse task log to be more human readable

### LINKED ISSUE #1275: task info printer needs improvements
When there are many tasks, it can become hard to read.

This becomes prominent with iamserviceaccounts, e.g.:

```
[ℹ]  3 sequential tasks: { delete nodegroup "ng-5b8f2f94", 2 sequential sub-tasks: { 2 sequential sub-tasks: { delete IAM role for serviceaccount "default/s3-reader", delete serviceaccount "default/s3-reader" }, delete IAM OIDC provider }, delete cluster control plane "irp-test-5-manual" [async] }
```

It'd look a bit better if we use multiple lines:
```
[ℹ]  3 sequential tasks: {
  delete nodegroup "ng-5b8f2f94", 2 sequential sub-tasks: {
    2 sequential sub-tasks: {
      delete IAM role for serviceaccount "default/s3-reader", delete serviceaccount "default/s3-reader"
    }
    delete IAM OIDC provider
  }
  delete cluster control plane "irp-test-5-manual" [async]
}
````

I think it help to present user this information, but still not sure what's the best way to convey it.

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Closes #1275.

New task log's appearance:

```
2021-10-04 11:50:49 [ℹ]  CloudWatch logging will not be enabled for cluster "log-formatting-test" in "us-west-2"
2021-10-04 11:50:49 [ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=us-west-2 --cluster=log-formatting-test'
2021-10-04 11:50:49 [ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "log-formatting-test" in "us-west-2"
2021-10-04 11:50:49 [ℹ]  2 sequential tasks: { create cluster control plane "log-formatting-test",
    2 sequential sub-tasks: {
        wait for control plane to become ready,
        create managed nodegroup "managed-ng-1",
    }
}2021-10-04 11:50:49 [ℹ]  building cluster stack "eksctl-log-formatting-test-cluster"
2021-10-04 11:50:51 [ℹ]  deploying stack "eksctl-log-formatting-test-cluster"
2021-10-04 11:51:21 [ℹ]  waiting for CloudFormation stack "eksctl-log-formatting-test-cluster"
```

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by aclevername** [comment]
Could it get updated to:
```
2021-10-04 11:50:49 [ℹ]  2 sequential tasks: { 
2021-10-04 11:50:49 [ℹ]      create cluster control plane "log-formatting-test",
2021-10-04 11:50:49 [ℹ]      2 sequential sub-tasks: {
2021-10-04 11:50:49 [ℹ]         wait for control plane to become ready,
2021-10-04 11:50:49 [ℹ]         create managed nodegroup "managed-ng-1",
2021-10-04 11:50:49 [ℹ]      }
2021-10-04 11:50:49 [ℹ] }
```

consistent indentation makes it a bit easier to read? wdyt?

**Comment by Skarlso** [comment]
> Could it get updated to:
> 
> ```
> 2021-10-04 11:50:49 [ℹ]  2 sequential tasks: { 
> 2021-10-04 11:50:49 [ℹ]      create cluster control plane "log-formatting-test",
> 2021-10-04 11:50:49 [ℹ]      2 sequential sub-tasks: {
> 2021-10-04 11:50:49 [ℹ]         wait for control plane to become ready,
> 2021-10-04 11:50:49 [ℹ]         create managed nodegroup "managed-ng-1",
> 2021-10-04 11:50:49 [ℹ]      }
> 2021-10-04 11:50:49 [ℹ] }
> ```
> 
> consistent indentation makes it a bit easier to read? wdyt?

Nope. And if you like, I can, IN LENGTH, explain why not and why it would be insanely painful and ugly code with a bunch of ifs fiddling the indentation. :D

**Comment by aclevername** [comment]
> > Could it get updated to:
> > ```
> > 2021-10-04 11:50:49 [ℹ]  2 sequential tasks: { 
> > 2021-10-04 11:50:49 [ℹ]      create cluster control plane "log-formatting-test",
> > 2021-10-04 11:50:49 [ℹ]      2 sequential sub-tasks: {
> > 2021-10-04 11:50:49 [ℹ]         wait for control plane to become ready,
> > 2021-10-04 11:50:49 [ℹ]         create managed nodegroup "managed-ng-1",
> > 2021-10-04 11:50:49 [ℹ]      }
> > 2021-10-04 11:50:49 [ℹ] }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > consistent indentation makes it a bit easier to read? wdyt?
> 
> Nope. And if you like, I can, IN LENGTH, explain why not and why it would be insanely painful and ugly code with a bunch of ifs fiddling the indentation. :D

could we instead do this then?

```
2021-10-04 11:50:49 [ℹ]  tasks:
2 sequential tasks: { create cluster control plane "log-formatting-test",
    2 sequential sub-tasks: {
        wait for control plane to become ready,
        create managed nodegroup "managed-ng-1",
    }
}
2021-10-04 11:50:49 [ℹ]  building cluster stack "eksctl-log-formatting-test-cluster"
```

**Comment by Skarlso** [comment]
> > > Could it get updated to:
> > > ```
> > > 2021-10-04 11:50:49 [ℹ]  2 sequential tasks: { 
> > > 2021-10-04 11:50:49 [ℹ]      create cluster control plane "log-formatting-test",
> > > 2021-10-04 11:50:49 [ℹ]      2 sequential sub-tasks: {
> > > 2021-10-04 11:50:49 [ℹ]         wait for control plane to become ready,
> > > 2021-10-04 11:50:49 [ℹ]         create managed nodegroup "managed-ng-1",
> > > 2021-10-04 11:50:49 [ℹ]      }
> > > 2021-10-04 11:50:49 [ℹ] }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > consistent indentation makes it a bit easier to read? wdyt?
> > 
> > 
> > Nope. And if you like, I can, IN LENGTH, explain why not and why it would be insanely painful and ugly code with a bunch of ifs fiddling the indentation. :D
> 
> could we instead do this then?
> 
> ```
> 2021-10-04 11:50:49 [ℹ]  tasks:
> 2 sequential tasks: { create cluster control plane "log-formatting-test",
>     2 sequential sub-tasks: {
>         wait for control plane to become ready,
>         create managed nodegroup "managed-ng-1",
>     }
> }
> 2021-10-04 11:50:49 [ℹ]  building cluster stack "eksctl-log-formatting-test-cluster"
> ```

yeah, that goes

**Comment by Skarlso** [comment]
Log format is now:

```
2021-10-04 15:01:17 [ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-west-2 --cluster=log-formatting-test'
2021-10-04 15:01:17 [ℹ]  CloudWatch logging will not be enabled for cluster "log-formatting-test" in "us-west-2"
2021-10-04 15:01:17 [ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=us-west-2 --cluster=log-formatting-test'
2021-10-04 15:01:17 [ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "log-formatting-test" in "us-west-2"
2021-10-04 15:01:17 [ℹ]
2 sequential tasks: { create cluster control plane "log-formatting-test",
    2 sequential sub-tasks: {
        wait for control plane to become ready,
        create managed nodegroup "managed-ng-1",
    }
}
2021-10-04 15:01:17 [ℹ]  building cluster stack "eksctl-log-formatting-test-cluster"
2021-10-04 15:01:19 [ℹ]  deploying stack "eksctl-log-formatting-test-cluster"
```

**Review by aclevername — APPROVED** [review]

**Comment by aclevername** [comment]
worth waiting for 2 reviewers before merging IMO

**Review by Himangini — APPROVED** [review]
⭐

**Pull request merged**
