### PR TITLE
Update the AMI list to use CVE-patched versions

### PR DESCRIPTION
**Pull request by toricls**
### Description

~**This PR depends on #532.**~ it's merged.

Regarding AWS’s security bulletin here: https://aws.amazon.com/security/security-bulletins/AWS-2019-002/

### Checklist
- [x] Code compiles correctly (i.e `make build`)
- [x] Added tests that cover your change (if possible)
- [x] All unit tests passing (i.e. `make test`)

### CODE REVIEW

**Comment by errordeveloper** [comment]
#532 was merged.

**Comment by errordeveloper** [comment]
By the way, 0.1.20-rc.5 is planned to go out later today (due to a regression in rc.4).

**Comment by toricls** [comment]
> rebase and run tests

done :)

**Comment by errordeveloper** [comment]
Once again, thanks a lot for a timely update!

**Comment by errordeveloper** [comment]
FYI: Looks like we will be able to cut 0.1.20 instead of 0.1.20-rc.5.

**Comment by toricls** [comment]
awesome, looking forward to seeing it :)

**Pull request merged**
