### PR TITLE
Add x-kubernetes-group-version-kind to Schema

### PR DESCRIPTION
**Pull request by noseworthy**
### Description

IntelliJ requires the root definition of a JSON config to include the
"x-kubernetes-group-version-kind" field in order for it to understand
the schema:

  - https://www.jetbrains.com/help/idea/kubernetes.html#crd

Add this field to the schema so that it's discoverable by IntelliJ.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by noseworthy** [comment]
Oh! Awesome! Thanks for pointing me in the right direction! I'll fix it up right away 😄

**Comment by noseworthy** [comment]
Hey @michaelbeaumont, I've updated the PR. Apologies if it's way off base. I'm not a go developer and this is my first go PR haha. The generate utility seems to generate the schema I was going for. 

Sorry there's no automated test for this, but I wasn't quite sure where to put it or how to go about testing this. Thanks for taking a look!

**Review by michaelbeaumont — APPROVED** [review]

**Comment by michaelbeaumont** [comment]
@noseworthy Thanks for the PR!

**Comment by noseworthy** [comment]
> @noseworthy Thanks for the PR!

My pleasure! Thanks for your work on the project!

**Pull request merged**
