### PR TITLE
Fix support for ap-east-1 region and Ubuntu1804 image family on Kubernetes 1.13

### LINKED ISSUE #1206: Fix support for ap-east-1 region and Ubuntu1804 image family on Kubernetes 1.13
The AMIs for region ap-east-1 (Hong Kong) are missing and the AMIs for Ubuntu1804 for Kubernetes 1.13 are empty. This breaks support for ap-east-1 (on all versions) and Ubuntu1804 on Kubernetes 1.13.

Related: https://github.com/weaveworks/eksctl/issues/1152

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Fixes #1206 

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [x] All unit tests passing (i.e. `make test`)
- [x] Manually tested

### CODE REVIEW

**Comment by errordeveloper** [comment]
I think this prompts a patch release, at least just because Ubuntu images for 1.13 have become available. Did you manage to find what changed in AL2 AMIs?

**Comment by cPu1** [comment]
> Did you manage to find what changed in AL2 AMIs?

From their release notes page and since we last updated the AMIs in July:

> Amazon Linux 2 - 7/18/2019 Update
> 
> An AWS-optimized Linux kernel 4.19 is now available in Amazon Linux 2 Extras channel in addition to the 4.14 kernel that receives long-term support. You can install and use the 4.19 kernel by running sudo amazon-linux-extras install kernel-ng and rebooting your instance.

**Comment by errordeveloper** [comment]
Ok, so it sounds like Ubuntu nodes for 1.13 are the most significant reason for getting a patch release out.

**Comment by cPu1** [comment]
That and also because ap-east-1 (Hong Kong) was broken.

**Pull request merged**
