### PR TITLE
Update aws-go-sdk to an ipv6 supported version

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Fixing the TODO in https://github.com/weaveworks/eksctl/pull/4571

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by cPu1 — APPROVED** [review]
LGTM.

Running `go mod tidy` removes a bunch of statements for me. Can we do that before merging?

**Comment by Skarlso** [comment]
@cPu1 Yep, for sure

**Comment by Skarlso** [comment]
Interesting, it only removed two lines for me 🤔

**Review by cPu1 — APPROVED** [review]

**Comment by Skarlso** [comment]
Damn it. Looks like it's not a straight update. :/

**Review by Himangini — APPROVED** [review]

**Pull request merged**
