### PR TITLE
[WIP] Experimental command: export-templates

### PR DESCRIPTION
**Pull request by errordeveloper**
### Description

This replaces #718.

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [ ] Added tests that cover your change (if possible)
- [ ] All unit tests passing (i.e. `make test`)
- [ ] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [x] Manually tested

### CODE REVIEW

**Comment by errordeveloper** [comment]
@pawelprazak the idea of putting this under `eksctl experimental` is so that we could ship this sooner, and improve before moving under utils or some other place.

**Comment by gemagomez** [comment]
After discussion with Ilya and the team, we decided to not have an experimental flag, and have an environment variable that enables experimental features instead. #1055 has been created to deal with experimental features.

**Comment by errordeveloper** [comment]
There is a new challenge with this, we will need to ignore `cloudWatch.clusterLogging`  and warn the user, that is because this is currently handled outside if CloudFormation. There are likely to be other features like this, as CloudFormation tends to be behind EKS.

**Comment by pawelprazak** [comment]
Yes, one that I know of is private API access.

**Comment by martina-if** [comment]
Closing until this comes back into our planning

**Pull request closed without merging**
