### PR TITLE
Remove outdated and generated version/release.go

### PR DESCRIPTION
**Pull request by rndstr**
The file `pkg/version/release.go` is generated when doing a release
through `tag-release.sh` and also committed into its release branch but
never merged back to master.

The one in master is from before we changed this process and can be
confusing for third parties vendoring and seeing the code with an
outdated tag.

### CODE REVIEW

**Comment by martina-if** [comment]
Should we just commit it when we release instead? It might be useful because then when we run `eksctl version` locally we would get the actual version instead of `[ℹ]  version.Info{BuiltAt:"1570548488", GitCommit:"0.2.0-565-gef183767", GitTag:""}`. https://github.com/weaveworks/eksctl/issues/1282

What do you think?

**Comment by rndstr** [comment]
we already do commit it when we release but never merge it back into master i think. also the tag only lives in the `release-X.Y` branch that's why the `GitCommit` only finds 0.2.0 in parent commits (which is what `git describe` does)

**Comment by martina-if** [comment]
can we commit it before branching out?

**Comment by rndstr** [comment]
@martina-if that won't update it for bugfix releases

**Comment by martina-if** [comment]
Ok, if @errordeveloper agrees I'm fine with merging this

**Pull request merged**
