### PR TITLE
fixing #1012, cluster autoscaler requres a valid LT intance type

### PR DESCRIPTION
**Pull request by alexei-led**
Kubernetes cluster autoscaler (AWS) requres a valid LT intance type to scale up/down ASG. See #1012 

### Description

Adding first instance type from distribution instance types as a default `LaunchTemplate` instance type.

### Checklist
- [x] Code compiles correctly (i.e `make build`)
- [x] Updated tests that cover your change 
- [x] All unit tests passing (i.e. `make test`)
- [x] Manually tested

### CODE REVIEW

**Comment by errordeveloper** [comment]
@alexei-led thanks for this PR! This looks good overall, but I'm just not sure if there are any implications on functionality, would you mind to provide a reference to AWS docs that suggests what does it mean when mixed instances are set along with traditional instance type?

**Comment by alexei-led** [comment]
@errordeveloper Ilya take a look at [AWS LaunchTemplate API docs](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_LaunchTemplate.html)

>> The overrides are used to override the instance type specified by the launch template with multiple instance types that can be used to launch On-Demand Instances and Spot Instances. 

i.e. when LT has `Overrides` section the `instanceType` in LT is ignored. I've also checked this.

**Comment by martina-if** [comment]
:+1: Thanks @alexei-led . I tested this creating 3 nodegroups: all spot instances, all on demand and mixed instances and it seems to work fine.

**Comment by errordeveloper** [comment]
Let's merge it for 0.2.0. We have 0.1.40 underway, and I'd prefer that to fix exactly one bug (#1003).

**Comment by whereisaaron** [comment]
@errordeveloper is `m5` a good choice for this? Remember that some AZ's don't have `m5` instances like `ap-southeast-2b`. Will that affect being able to use this change in that zone, or will the override prevent any errors.

**Comment by alexei-led** [comment]
@whereisaaron any non-empty string is a good choice - cluster autoscaler validates only that `instanceType` is not empty, no actual validation is done :)

**Pull request merged**
