### PR TITLE
Do not panic when NodeAffinity unset on older KubeProxy versions

### LINKED ISSUE #4245: panic in addArm64NodeSelector when upgrading kube-proxy
**What were you trying to accomplish?**

I was attempting to upgrade the kube-proxy component in my aws cluster by running `eksctl utils upgrade-kube-proxy --cluster ....`

**What happened?**

I get the following output:

```
2021-09-23 16:28:01 [ℹ]  eksctl version 0.67.0
2021-09-23 16:28:01 [ℹ]  using region us-east-1
2021-09-23 16:28:02 [ℹ]  missing arm64 nodeSelector value
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x29f4c55]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/addons/default.addArm64NodeSelector(0xc000fa09a0, {0x3aca9c6, 0x3ae9f67})
	github.com/weaveworks/eksctl/pkg/addons/default/kube_proxy.go:153 +0x35
github.com/weaveworks/eksctl/pkg/addons/default.UpdateKubeProxy({0x4013e10, 0xc000f2e000}, {0xc000267cf0, 0x7}, 0x0)
	github.com/weaveworks/eksctl/pkg/addons/default/kube_proxy.go:122 +0x594
github.com/weaveworks/eksctl/pkg/ctl/utils.doUpdateKubeProxy(0xc000534210)
	github.com/weaveworks/eksctl/pkg/ctl/utils/update_kube_proxy.go:62 +0x12c
github.com/weaveworks/eksctl/pkg/ctl/utils.updateKubeProxyCmd.func1(0xc00015a280, {0xc0007ba7e0, 0x7, 0x7})
	github.com/weaveworks/eksctl/pkg/ctl/utils/update_kube_proxy.go:20 +0x59
github.com/spf13/cobra.(*Command).execute(0xc00015a280, {0xc0007ba770, 0x7, 0x7})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005c8c80)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/weaveworks/eksctl/cmd/eksctl/main.go:99 +0x525
```

It appears to be coming from [here](https://github.com/weaveworks/eksctl/blob/main/pkg/addons/default/kube_proxy.go#L153-L161).

**How to reproduce it?**

Have the following kube-proxy daemonset running on your cluster:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "10"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"eks.amazonaws.com/component":"kube-proxy","k8s-app":"kube-proxy"},"name":"kube-proxy","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"kube-proxy"}},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"k8s-app":"kube-proxy"}},"spec":{"containers":[{"command":["/bin/sh","-c","kube-proxy --resource-container=\"\" --oom-score-adj=-998 --master=https://59eba41dbb3e69921e4d0af76b2814ee.yl4.us-east-1.eks.amazonaws.com --kubeconfig=/var/lib/kube-proxy/kubeconfig --proxy-mode=iptables --v=2 1\u003e\u003e/var/log/kube-proxy.log 2\u003e\u00261"],"image":"602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.10.3","name":"kube-proxy","resources":{"requests":{"cpu":"100m"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/log","name":"varlog","readOnly":false},{"mountPath":"/run/xtables.lock","name":"xtables-lock","readOnly":false},{"mountPath":"/var/lib/kube-proxy/","name":"kubeconfig"}]}],"hostNetwork":true,"serviceAccountName":"kube-proxy","tolerations":[{"effect":"NoExecute","operator":"Exists"},{"effect":"NoSchedule","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/var/log"},"name":"varlog"},{"hostPath":{"path":"/run/xtables.lock","type":"FileOrCreate"},"name":"xtables-lock"},{"configMap":{"name":"kube-proxy"},"name":"kubeconfig"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":"10%"},"type":"RollingUpdate"}}}
  creationTimestamp: "2018-08-29T12:55:10Z"
  generation: 10
  labels:
    eks.amazonaws.com/component: kube-proxy
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "196859403"
  selfLink: /apis/apps/v1/namespaces/kube-system/daemonsets/kube-proxy
  uid: c339a828-ab8a-11e8-a044-12c352781cb6
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - kube-proxy --resource-container="" --oom-score-adj=-998 --master=https://59eba41dbb3e69921e4d0af76b2814ee.yl4.us-east-1.eks.amazonaws.com
          --kubeconfig=/var/lib/kube-proxy/kubeconfig --proxy-mode=iptables --v=2
          1>>/var/log/kube-proxy.log 2>&1
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.15.11
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        resources:
          requests:
            cpu: 100m
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /var/lib/kube-proxy/
          name: kubeconfig
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-proxy
      serviceAccountName: kube-proxy
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - configMap:
          defaultMode: 420
          name: kube-proxy
        name: kubeconfig
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 10
  updatedNumberScheduled: 3
```

attempt to run `eksctl utils upgrade-kube-proxy --cluster ...` and see the error 

**Logs**

**Anything else we need to know?**

darwin
downloaded binary
profile

**Versions**

```
$ eksctl info
eksctl version: 0.67.0
kubectl version: v1.21.4
OS: darwin
```

### PR DESCRIPTION
**Pull request by NaivePa**
### Description
Fix #4245 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Callisto13** [comment]
Thanks 👍 

Could you please add a test and ensure that the linter passes.

**Comment by Himangini** [comment]
@NaivePa is this still WIP? do you require any help with this? feel free to reach we're happy to help :)

**Comment by Skarlso** [comment]
I actually don't think this is the right fix here. This would skip this function when it's supposed to add things on the missing nodeselectors. I'm not sure it also needs to create the selectors, but I have a hunch, that it should. It needs a bit of further investigation, and a test first approach to first reproduce the bug then identify the desired actual behaviour. 

Author of this PR has been absent and this issue needs to be resolved, so I'm taking over the fix. Thank you for your PR! Please try and pick a new issue if you would like to contribute to `eksctl`. We have a couple good first issues for first time contributors. :)

**Comment by NaivePa** [comment]
I apologise for being off topic for a while. I noticed that @Skarlso took over my PR, and I appreciate it. I apologise on my end.

**Pull request closed without merging**
