### PR TITLE
feat(nodegroup): Integrate Spot Ocean with Nodegroups

### PR DESCRIPTION
**Pull request by liranp**
### Description

Similarly to the existing [integration with kops instance groups](https://kops.sigs.k8s.io/getting_started/spot-ocean/), this PR seamlessly integrates [Ocean](https://spot.io/products/ocean/) by [Spot](https://spot.io/) with unmanaged nodegroups, as a drop-in replacement for AWS Auto Scaling groups.

### Usage

To create a new Ocean nodegroup, run:

```bash
eksctl create nodegroup \
  --cluster <cluster-name> \
  --nodegroup-name <nodegroup-name> \
  --spot-ocean
```

To create multiple nodegroups and have more control over the configuration, a config file can be used:

```yaml
# cluster.yaml
# A cluster with an unmanaged nodegroup and an Ocean-managed nodegroup.
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: example
  region: us-west-2
nodeGroups:

# Use Ocean.
- name: ocean-ng-1
  minSize: 2
  maxSize: 4

  # Enable Ocean integration with all defaults.
  # Please see the documentation for a list of available options.
  spotOcean: {} 

# Use AWS Auto Scaling group.
- name: ng-2
  minSize: 2
  maxSize: 3
```

### Documentation

Full documentation, with usage examples, can be found [here](https://github.com/spotinst/weaveworks-eksctl/blob/f6513ed1f05ef48b4b3819f98c4253b3d1915480/userdocs/src/usage/spot-ocean-nodegroups.md).

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by michaelbeaumont** [comment]
Hi @liranp, as[mentioned in the previous PR](https://github.com/weaveworks/eksctl/pull/1015#issuecomment-544546128), can you please open an issue outlining and describing the feature where we can discuss it?

**Comment by liranp** [comment]
@martina-if Why did you close the PR?

**Comment by martina-if** [comment]
Hi @liranp, sorry about that, I should have added a comment. I closed it based on [this comment](https://github.com/weaveworks/eksctl/issues/2364#issuecomment-669196562).

**Comment by mavogel** [comment]
hi @martina-if could you re-open it based on this [comment](https://github.com/weaveworks/eksctl/issues/2364#issuecomment-672951883) and upvotes :)

We use it as well and would welcome this feature. Currently, we use the binary from the forked project.

**Comment by martina-if** [comment]
@markramm @michaelbeaumont

**Comment by joshdlee** [comment]
Can you please reopen this, I want these ocean features @martina-if

**Pull request closed without merging**
