### PR TITLE
Update error msg in DescribeControlPlane function

### PR DESCRIPTION
**Pull request by pradeepnnv**
Update the error message in
DescribeControlPlane function to
include region.

Fixes https://github.com/weaveworks/eksctl/issues/2980

Signed-off-by: pradeepnnv <pradeepnnv@gmail.com>

### Description

Included the region in the error message if cluster is not available in the region.

```
./eksctl get iamidentitymapping --cluster=foo
Error: unable to fetch cluster status to determine operability: Unable to describe cluster control plane in the region "us-east-1": ResourceNotFoundException: No cluster found for name: foo.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "f4b41b52-d86f-4005-94fa-ff35fb712e44"
  },
  Message_: "No cluster found for name: foo."
}
```

```
./eksctl get fargateprofile --cluster=foo
Error: Unable to describe cluster control plane in the region "us-east-1": ResourceNotFoundException: No cluster found for name: foo.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "5d6f934d-8121-480c-8d7f-5e288bb81549"
  },
  Message_: "No cluster found for name: foo."
}
```

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [ ] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by Callisto13** [comment]
Would you be able to also improve the other commands which do not return region in the error? `get cluster`, `get labels`, `get nodegroups` are some that I have found, there may be others.

Also what do you think about the UX of the errors/logs we return in these commands? Other commands return neater errors on lower logging levels, and most of them have a nice logging pattern where the region is mentioned, eg:

```sh
$ eksctl delete cluster foo
[ℹ]  eksctl version 0.34.0
[ℹ]  using region us-west-2
[ℹ]  deleting EKS cluster "foo"
Error: no eksctl-managed CloudFormation stacks found for "foo"
```

The logging pattern doesn't seem to be applied for `get` commands, I wonder if that was a deliberate decision 🤔 . It could be one way of communicating the region.

So 2 things to consider for this improvement:
1. Is just dumping out the error from these failures (`RespMetadata` etc) useful for users who have a low logging level set? Can/should we tidy that up?
2. Would it be nice, useful and consistent UX to add that nice logging to all commands?

**Comment by pradeepnnv** [comment]
Sure @Callisto13. Let me review the other get commands and their error messages.

**Comment by pradeepnnv** [comment]
@Callisto13 , I added the same logging available in delete to all get commands.

Commands `get addon`, `get cluster`, `get fargateprofile` and `get iamidentitymapping` are printing the region as expected.

```
./eksctl get iamidentitymapping  --cluster=foo

[ℹ]  eksctl version 0.37.0-dev+7a358ddf.2021-01-10T15:06:08Z
[ℹ]  using region us-west-2
Error: unable to fetch cluster status to determine operability: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: foo.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "94a68e72-022a-4ebf-afbb-e50f34d05e72"
  },
  Message_: "No cluster found for name: foo."
}

   ./eksctl get cluster

[ℹ]  eksctl version 0.37.0-dev+7a358ddf.2021-01-10T15:06:08Z
[ℹ]  using region us-west-2
No clusters found
```

But the other get commands `get iamserviceaccount`, `get labels` and `get nodegroup` are not having the region value. Hence region is being printed as an empty string. Weirdly, this is the same case even if we pass the region as an argument.

```
 ./eksctl get iamserviceaccount  --cluster=foo --region=us-east-1
[ℹ]  eksctl version 0.37.0-dev+7a358ddf.2021-01-10T15:06:08Z
[ℹ]  using region
Error: unable to fetch cluster status to determine operability: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: foo.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "a6663362-fdc0-4273-aa87-529087662386"
  },
  Message_: "No cluster found for name: foo."
}
```

Any idea what's happening here?

**Comment by Callisto13** [comment]
Looking good 😃 .

🤔  It is probably because where you are doing `cmdutils.LogRegionAndVersionInfo(cmd.ClusterConfig.Metadata)` for those, the region has not been set in that Metadata yet (the flag has not been parsed into the config). Try moving it to after `cmd.NewCtl` and it should be on either the `ProviderConfig` or the `ClusterConfig`.

 Also, some commands (`get cluster` off the top of my head) have an "all" `-A` flag, in that case the logging behaviour may need to change a bit so that the region makes sense.

**Comment by pradeepnnv** [comment]
Thanks. That helped. Now the region is printed in all get commands.

Also, I added a check to not print the region if all regions option is selected in get cluster command. That's the only one which accepts all regions flag.

**Review by Callisto13 — APPROVED** [review]
Awesome! Thanks @pradeepnnv 🎉

**Pull request merged**
