### PR TITLE
Also push v prefixed tags on release

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by aclevername — COMMENTED** [review]
is there a way we don't have to do both? I know we tried just doing it with the v prefix before and it didn't work, but I don't recall why

**Comment by michaelbeaumont** [comment]
Mostly because I didn't want to change the names of the releases (i.e. users expect `releases/x.y.z` and not `release/vx.y.z`. It should be changed, but I didn't want to "break" things yet.

**Review by aclevername — COMMENTED** [review]
LGTM

**Review by aclevername — APPROVED** [review]

**Comment by michaelbeaumont** [comment]
@aclevername Switching to release branch

**Pull request merged**
