### PR TITLE
Set effective AWS credentials explicitly as environment variables for kubectl checks

### LINKED ISSUE #71: MFA errors when checking dependencies
If you are using MFA there are 2 errors reported from `CheckAllCommands`. Specifically when getting the kubectl version and then when checking the server version:
```bash
2018-06-19T17:20:17+01:00 [▶]  kubectl: "/usr/local/bin/kubectl"
2018-06-19T17:20:17+01:00 [▶]  clientVersion="v1.10.2" err="Assume Role MFA token code: could not get token: EOF\nUnable to connect to the server: getting token: exec: exit status 1\n"
2018-06-19T17:20:17+01:00 [▶]  heptio-authenticator-aws: "/Users/richardcase/bin/heptio-authenticator-aws"
2018-06-19T17:20:17+01:00 [✖]  unable to use kubectl with the EKS cluster (check ' --kubeconfig /Users/richardcase/.kube/config version'): Assume Role MFA token code: could not get token: EOF
Unable to connect to the server: getting token: exec: exit status 1
2018-06-19T17:20:17+01:00 [ℹ]  cluster should be functions despite missing client binaries that need to be installed in the PATH
```

Potentially the following should happen:
- Only get the client version in `CheckKubectlVersion`. This would be by setting `--client=true`
- Not checking the server version in `CheckAllCommands`. As it stands eksctl doesn't allow you to specify a Kubernetes version (i.e. it gets the latest version supported by EKS). Should we expose a version flag then we can check its above the minimum version supported.

### PR DESCRIPTION
**Pull request by errordeveloper**
Fixes #71.

### CODE REVIEW

**Comment by richardcase** [comment]
I've been testing and i don't get the error anymore but there appears to be something wrong with the output:

```bash
2018-07-11T20:04:20+01:00 [▶]  clientVersion="v1.11.0" err=%!!(MISSING)q(<nil>)
2018-07-11T20:04:20+01:00 [▶]  heptio-authenticator-aws: "/Users/richardcase/bin/heptio-authenticator-aws"
2018-07-11T20:04:21+01:00 [ℹ]  kubectl command should work with "/Users/richardcase/.kube/config", try 'kubectl --kubeconfig=/Users/richardcase/.kube/config get nodes'
2018-07-11T20:04:21+01:00 [✔]  EKS cluster "richtest17" in "us-west-2" region is ready
```

And it asked me for my credentials multiple times still. I will run some more tests in the morning.

**Comment by richardcase** [comment]
I also noticed someting weird when using `--auto-kubeconfig`, i need to investigate further.

**Comment by errordeveloper** [comment]
> ...there appears to be something wrong with the output

I'll tidy this up.

> And it asked me for my credentials multiple times still. I will run some more tests in the morning.

How many exactly?

**Comment by richardcase** [comment]
It asked twice. Once at the beginning at time `2018-07-11T19:38:41+01:00` and then again at `2018-07-11T19:55:51+01:00`. Looking at the times that makes sense as the default SessionDuration is 900 seconds (15 mins). 

I'll have a look to see if we can update this duration when we create the session.

**Comment by richardcase** [comment]
Checking the new commits now.

**Comment by errordeveloper** [comment]
> richcase [10:49 AM]
> Testing has worked for me.
> Great work
> And only 1 MFA prompt at the beginning

**Comment by richardcase** [comment]
It worked.

```bash
2018-07-12T10:07:08+01:00 [ℹ]  the cluster has 1 nodes
2018-07-12T10:07:08+01:00 [ℹ]  node "ipxxxxx.us-west-2.compute.internal" is ready
2018-07-12T10:07:08+01:00 [▶]  kubectl: "/usr/local/bin/kubectl"
2018-07-12T10:07:10+01:00 [▶]  kubectl version: v1.11.0
2018-07-12T10:07:10+01:00 [▶]  heptio-authenticator-aws: "/Users/richardcase/bin/heptio-authenticator-aws"
2018-07-12T10:07:11+01:00 [ℹ]  kubectl command should work with "/Users/richardcase/.kube/config", try 'kubectl --kubeconfig=/Users/richardcase/.kube/config get nodes'
2018-07-12T10:07:11+01:00 [✔]  EKS cluster "richtest18" in "us-west-2" region is ready
```

**Pull request merged**
