### PR TITLE
Support Create of Cluster with Private VPC Endpoint

### PR DESCRIPTION
**Pull request by morinap**
### Description
This enables the cluster to be created without public access while allowing the creator to specify a control plane security group that can allow bastion or other hosts on the VPC to access the control plane for further eksctl calls.

This works well for our use case; I created a security group that allows HTTPS access inbound from our bastion host before creating the cluster, and then I specified that security group under `VPC` in my cluster create YML.

This addresses https://github.com/weaveworks/eksctl/issues/1358

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [x] Manually tested

### CODE REVIEW

**Comment by D3nn** [comment]
Someone creating a new EKS cluster using the PR while NOT using an existing VPC/Bastion Host 
to run eksctl will currently fail since eksctl will not have access to the Kubernetes API to join the nodes to the security group as it now stands, at least not in the scenario where public access is disabled.

There are a couple of solutions where I think a single command approach might suffice:
1. This PR, but with up-front verification of prerequisites mentioned above being met (and possibly the newly created security group being used (and then discarded) in the creation of the ControlPlaneSecurityGroup).
1. We delay setting Public access to false until the worker nodes have been joined to the cluster. (Investigating this one currently)

**Comment by morinap** [comment]
@D3nn Thank you for the feedback; I can start down the path of meeting the 3 requisites you mentioned. Very good point about creating a cluster without an existing VPC; that's not my use case, and obviously it isn't something I'd considered because of that.

Just a couple of notes/questions:
* While it's true that the `ControlPlaneSecurityGroup` is created as part of cluster creation, I'm simply leveraging an existing code path that instead of creating that group modifies the specified group when one is specified in the VPC spec.
* Instead of allowing specification of a security group, the other (more complex) path we'd considered was to allow specification of a set of ingress rules to be automatically added to the `ControlPlaneSecurityGroup` when it's created. Does that seem more in line with a more robust solution you're looking for? And if so, any suggestions on the structure of such a definition?

**Comment by D3nn** [comment]
There are a few things that need to be fixed so we can merge:
1. There are generated files that no longer matching the previously existing generated files.  For these, you'll need to check in the new generated files to fix that circleci build error.
1. There are a few conflicts (humans.txt and site/content/usage/06-vpc-networking.md) which need to be resolved.

Please make these updatess so we can validate that circleci isn't failing (at least for these issues)

**Comment by morinap** [comment]
@D3nn I'm in the midst of some other things and may not have further time to work on this in the near future. Would you prefer for managing the project for me to leave this open and come back to it when I'm ready, or close it and open a new PR when I can address your feedback?

**Comment by D3nn** [comment]
Thanks for the update @morinap.  I have no issues leaving this open for the time being.

**Comment by martina-if** [comment]
Hi, I am doing a little bit of cleaning so I will be closing this but please feel free to reopen it whenever you have time to work on this again :)

**Pull request closed without merging**
