### PR TITLE
Add g3 support

### PR DESCRIPTION
**Pull request by Jeffwan**
### Description
Add g3 support in eksctl

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [x] Added tests that cover your change (if possible)
- [x] All unit tests passing (i.e. `make test`)
- [ ] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [ ] Manually tested

### CODE REVIEW

**Comment by Jeffwan** [comment]
BTW, I keep getting error when generate files.  I change `pkg/mod/k8s.io/code-generator@v0.0.0-20190612205613-18da4a14b22b` to the version on my mac to pass `make build` and `make test`.

**Comment by errordeveloper** [comment]
I am not sure why CI broke, I'm going to look into it now, but I doubt it's to do with this PR.

**Comment by errordeveloper** [comment]
`make eksctl-image` should work exactly the same locally.
 I've tried it on your branch locally and it succeeded, for some reason it's failing in CI at the moment.

**Comment by Jeffwan** [comment]
> `make eksctl-image` should work exactly the same locally.
> I've tried it on your branch locally and it succeeded, for some reason it's failing in CI at the moment.

Thanks! Any reason we have fixed version of pkg/mod/k8s.io/code-generator@v0.0.0-20190612205613-18da4a14b22b in Make file?

**Comment by errordeveloper** [comment]
Looks like the issue is with cache in CI:

```
No cache is found for key: go-cache-pull/1158-68c6a9844affe09549102a247a578fb3d48b820a
No cache is found for key: go-cache-pull/1158-
No cache is found for key: go-cache-
```

Normally it should say something like this:
```
No cache is found for key: go-cache-docs-bb87748d99219d4c19dcc7dd6ec1f6c36d84c79d
Found a cache from build 4247 at go-cache-docs-
Size: 2.5 GB
Cached paths:
  * /home/circleci/.cache/go-build
  * /home/circleci/go/pkg/mod

Downloading cache archive...
Unarchiving cache...
```

I'm gonna try to push this via another branch, it's possible cache doesn't work for forks.

**Comment by errordeveloper** [comment]
Merged #1194.

**Comment by Jeffwan** [comment]
Thanks!

**Pull request closed without merging**
