### PR TITLE
Fix: Misspelled serviceAccountRoleARN in documentation

### PR DESCRIPTION
**Pull request by itniels**
Hi, 
Was reading through the documentation, and spottet this misspelling.
I have not ran the commands, or tested it. but comparing to the yaml schema the CLI commands is mispelled. 🙂

### Checklist
- [] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [x] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by cPu1 — APPROVED** [review]
LGTM. Thanks for the PR!

**Comment by itniels** [comment]
Thanks for quick review 🙂

**Comment by itniels** [comment]
@cPu1 How is the workflow here, do you guys merge and close the PR when done or? 🙂

**Comment by Callisto13** [comment]
We handle that 😄  thanks @itniels

**Pull request merged**
