### PR TITLE
Add release notes for 0.37.0

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by aclevername — CHANGES_REQUESTED** [review]
why is this going into master 🤔 ? shouldn't it be going to the release branch?

**Comment by michaelbeaumont** [comment]
We usually merge them to master, it's not completely clear whether that makes sense. I think they'll end up on master in a lot of cases anyway? (if they started on `release-*` and then that branch was merged to master, for example)

**Review by aclevername — APPROVED** [review]
LGTM

**Comment by michaelbeaumont** [comment]
Not waiting for checks, nothing to test here.

**Pull request merged**
