### PR TITLE
Add LogRetentionInDays update to update-cluster-logging command

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Closes https://github.com/weaveworks/eksctl/issues/5294

### Checklist
- [x] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Skarlso** [comment]
Question:

This is only possible together if some kind of logging is enabled with it. So you can't just update the log retention period only together with something that is being enabled.

My suggestion is to lift this restriction and make it possible to update just the log retention period without having to enable/disable a log type.

**Review by cPu1 — APPROVED** [review]

**Review by Himangini — APPROVED** [review]
👍🏻

**Comment by fredcooke** [comment]
This is good - it'd be great it it could be configured in the yaml configuration side by side with the enabling of the types, though.

**Comment by cPu1** [comment]
> This is good - it'd be great it it could be configured in the yaml configuration side by side with the enabling of the types, though.

It can be enabled in the ClusterConfig file. Here's an [example](https://github.com/weaveworks/eksctl/blob/main/examples/11-cloudwatch-cluster-logging.yaml).

**Comment by kishoregv** [comment]
Currently, eksctl is only updating the log retention days only if there is any change on the log types that are enabled or disabled.

It would be nice if log retention days is idempotently updated regardless of change in the log types.

**Comment by Skarlso** [comment]
@kishoregv hi.

See this comment:
https://github.com/weaveworks/eksctl/pull/5404#issuecomment-1153584907

Basically, you'll have to change something together with enabling or disabling logging. You can't define it on its own.

**Pull request merged**
