### PR TITLE
Fix error message for delete nodegroup / drain nodegroup command

### PR DESCRIPTION
**Pull request by ghsbhatia**
Issue #1782

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`) and target version (e.g. `version/0.12.0`)
- [ ] Added note in `docs/release_notes/draft.md` (or relevant release note)

### CODE REVIEW

**Comment by sayboras** [comment]
@ghsbhatia thanks for your PR. I was kind of lazy and fixed this issue in https://github.com/weaveworks/eksctl/issues/1782. I should not have bundled so many things together though.

Our changes look good to me, would you please add some test cases for this change? The reference unit test can be found in https://github.com/weaveworks/eksctl/issues/1782.

**Comment by ghsbhatia** [comment]
@sayboras I looked at your pull request and this is already covered - I will withdraw my pull request.

**Comment by sayboras** [comment]
@ghsbhatia the related PR might take long time to review and approve. Ideally, I should have kept the PR small. So if you want, you can still add test cases and then send for review. :)

**Comment by martina-if** [comment]
Superseded by #2044

**Pull request closed without merging**
