### PR TITLE
WIP Remove support for 1.19

### LINKED ISSUE #5521: [Task] Remove support for EKS 1.19
### Description
As per the calendar for [Amazon EKS end of support](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) August 1, 2022 is the end of support for Kubernetes version 1.19 

We need to remove support for 1.19 and modify any relevant docs wherever possible.
Reference PR - see [here](https://github.com/weaveworks/eksctl/pull/5073)

### PR DESCRIPTION
**Pull request by neha-viswanathan**
fixes #5521 

### Description

remove support for 1.19

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested [test.txt](https://github.com/weaveworks/eksctl/files/9182342/test.txt)
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Himangini** [comment]
Thanks for the PR 🎉 Can you add the output of your manual testing as well, please?

**Comment by neha-viswanathan** [comment]
> Thanks for the PR 🎉 Can you add the output of your manual testing as well, please?

done @Himangini

**Review by Himangini — COMMENTED** [review]
Verified locally 🎉 
```
pr/5536 ✔ $ ./eksctl create cluster --name test-gini --version 1.19
2022-08-03 13:13:14 [ℹ]  eksctl version 0.109.0-dev+7b535518d.2022-08-03T13:10:01Z
2022-08-03 13:13:14 [ℹ]  using region us-east-1
Error: invalid version, 1.19 is no longer supported, supported values: 1.20, 1.21, 1.22
see also: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
```

Can you remove `sample-1.19.json` file too please. 👍🏻

**Review by Himangini — APPROVED** [review]
Need to remove `sample-1.19.json` file and it is good to go 👍🏻

**Comment by neha-viswanathan** [comment]
> Need to remove `sample-1.19.json` file and it is good to go 👍🏻

It looks like this file is needed for the coreDNS tests. Do I still need to remove it?

**Comment by Himangini** [comment]
> > Need to remove `sample-1.19.json` file and it is good to go 👍🏻
> 
> @Himangini It looks like this file is needed for the coreDNS tests. Do I still need to remove it?

oops my bad, i made a typo 🙈 Can you remove `sample-1.18.json` please?

**Review by Himangini — APPROVED** [review]

**Review by cPu1 — APPROVED** [review]
Thanks for the contribution.

There's user-facing documentation on managed nodegroups that is still using [1.19 as an example](https://github.com/weaveworks/eksctl/blob/main/userdocs/src/usage/eks-managed-nodes.md#upgrading-managed-nodegroups), but I think we can leave it as it's mainly for showing the format of the release version.

**Comment by cPu1** [comment]
GitHub has been acting weird on this PR, it's stuck on "Waiting for status to be reported", and won't let me merge it.

**Comment by Himangini** [comment]
@wip ready for review

**Comment by toabctl** [comment]
@Himangini @cPu1 why did you remove support for 1.19? This is still supported by EKS . See https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

**Pull request merged**
