### PR TITLE
Add new GPU instance type inf1 

### PR DESCRIPTION
**Pull request by regulusv**
### Description
This pull request is to add [Inf1](https://aws.amazon.com/ec2/instance-types/inf1/) with intstance type is GPU

changs in pkg/utils/utils.go to identify inf1 instance is GPU type instance

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `site/content` directory)
- [x] Manually tested
- [x] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by sayboras** [comment]
@regulusv inf1  seems not inside this list https://aws.amazon.com/marketplace/pp/B07GRHFXGM, and as far as I know it requires CNI 1.6 which is not default version fo EKS CNI right now. So is there any steps that you need to do manually during testing ?

**Comment by kalbir** [comment]
We want to change the message that users get when they create inf1 nodes so that it informs them to use the INF1 device plugin rather than the NVIDIA one.

**Comment by mikestef9** [comment]
CNI 1.6.1 will soon made the default version in new EKS clusters, and this is prerequisite for launching support for Inf1 instances

**Comment by sayboras** [comment]
> CNI 1.6.1 will soon made the default version in new EKS clusters, and this is prerequisite for launching support for Inf1 instances

@mikestef9 thanks for your info. It's awesome, a lot of interesting things going on with EKS :tada:

**Comment by mikestef9** [comment]
Doesn't look this PR is required anymore with #2134?

**Comment by michaelbeaumont** [comment]
The other PR adds the info message, this one causes the Accelerated AMI to be chosen

**Pull request merged**
