### PR TITLE
ARM Support Doc Update for un-managed NodeGroup users

### PR DESCRIPTION
**Pull request by joelachance**
## Description

Adds a note in the ARM Support docs for users not using managedNodeGroups. If using un-ma`ami: auto` or `ami: auto-ssm` naged NodeGroups,
using either ami: auto or ami: auto-ssm is a requirement.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [ ] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by martina-if** [comment]
Hi @joelachance this shouldn't be needed, what made you think one needs to specify this field as auto or auto-ssm? Is it an error you got?

**Comment by joelachance** [comment]
Hi @martina-if-- 

When not including the `ami: auto` or `ami: auto-ssm` AND using un-managed NodeGroups, CloudFormation errors out. If you use managed NodeGroups, you don't need this.

I agree, it would be great if it didn't need to be included for either configuration! I invite you to give it a shot.

**Comment by martina-if** [comment]
@joelachance 

I tested this yesterday with

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: martina-arm-1
  region: us-west-2

nodeGroups:
  - name: ng-arm-1
    instanceType: m6g.medium
    desiredCapacity: 1
```

and I didn't see any errors. Can you please post the full logs here? It should not be like that so it might be a bug that we need to fix instead of fixing the docs.

**Comment by joelachance** [comment]
@martina-if 
Oh, thank you! Your Cluster config worked great, and I'm realizing I had given it a non-eksctl `apiVersion`. I'll close this.

Have a great week,

**Pull request closed without merging**
