### PR TITLE
Update aws-node util to 1.11

### LINKED ISSUE #5336: [Bug] Updating aws-node with utils installs not the recommended version
### What were you trying to accomplish?

Updating aws-node to the newest recommended version with the use of `eksctl utils update-aws-node `

### What happened?

Version v1.9.3 gets installed, instead of the recommended version 1.11.0 (https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-add-on)

When manually fixing the image i ran into another problem which seems to be related to the missing new env variables ENABLE_IPv6 and ENABLE_IPv4 which were introduced in the newer versions of aws-node (https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.10/config/master/aws-k8s-cni.yaml). In the reference manifest IPv4 is enabled by default. It seems like both parameters have to be set explicitly.

IPv4 as default would be fine for me, but it seems there is more logic needed if that should be configurable.

### How to reproduce it?

`eksctl utils update-aws-node `

**Logs**

Updating the Image without the new env variables:
```
{"level":"error","ts":"2022-05-27T14:04:19.289Z","caller":"ipamd/ipamd.go:406","msg":"IPv4 and IPv6 are both disabled. One of them have to be enabled"}
```

**Anything else we need to know?**

least available eksctl on mac

**Versions**
```
$ eksctl info
eksctl version: 0.83.0
kubectl version: v1.23.2
OS: darwin
```

### PR DESCRIPTION
**Pull request by steveizzle**
Signed-off-by: steveizzle <stefan.riembauer@gmail.com>

### Description

Closes #5336 

Update of the aws-node to the last recommended version from aws with the default manifest. 

### Checklist
- [X] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [X] Manually tested
- [X] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Skarlso** [comment]
hi @steveizzle !

Please include a complete manual test run with this dev version :) thank you!

**Comment by steveizzle** [comment]
@Skarlso Sure, here you go! 

(make test was successfull without error, following is the output of my manual test)

**Manual Tests:**

_Test environment_
```
k get ds aws-node -n kube-system -o wide
NAME       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE    CONTAINERS   IMAGES                                                                  SELECTOR
aws-node   49        49        49      49           49          <none>          179d   aws-node     602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.9.3   k8s-app=aws-node

k version 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:51Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-14c7a48", GitCommit:"35f06c94ad99b78216a3d8e55e04734a85da3f7b", GitTreeState:"clean", BuildDate:"2022-04-01T03:18:05Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

```

_With current eksctl version_
```
eksctl version
0.99.0

eksctl utils update-aws-node test-cluster
2022-05-31 09:08:23 [ℹ]  (plan) would have skipped existing "kube-system:ServiceAccount/aws-node"
2022-05-31 09:08:23 [ℹ]  (plan) would have replaced "ClusterRoleBinding.rbac.authorization.k8s.io/aws-node"
2022-05-31 09:08:23 [ℹ]  (plan) would have replaced "ClusterRole.rbac.authorization.k8s.io/aws-node"
2022-05-31 09:08:23 [ℹ]  (plan) would have replaced "CustomResourceDefinition.apiextensions.k8s.io/eniconfigs.crd.k8s.amazonaws.com"
2022-05-31 09:08:23 [ℹ]  (plan) would have replaced "kube-system:DaemonSet.apps/aws-node"
2022-05-31 09:08:23 [ℹ]  (plan) "aws-node" is already up-to-date
```

__With dev version__

```
eksctl version
0.101.0-dev+059c8d9.2022-05-30T13:17:26Z

eksctl utils update-aws-node test-cluster
2022-05-31 09:09:54 [ℹ]  (plan) would have skipped existing "kube-system:ServiceAccount/aws-node"
2022-05-31 09:09:54 [ℹ]  (plan) would have replaced "CustomResourceDefinition.apiextensions.k8s.io/eniconfigs.crd.k8s.amazonaws.com"
2022-05-31 09:09:54 [ℹ]  (plan) would have replaced "ClusterRole.rbac.authorization.k8s.io/aws-node"
2022-05-31 09:09:54 [ℹ]  (plan) would have replaced "ClusterRoleBinding.rbac.authorization.k8s.io/aws-node"
2022-05-31 09:09:54 [ℹ]  (plan) would have replaced "kube-system:DaemonSet.apps/aws-node"
2022-05-31 09:09:54 [✖]  (plan) "aws-node" is not up-to-date
2022-05-31 09:09:54 [!]  no changes were applied, run again with '--approve' to apply the changes

eksctl utils update-aws-node eks-ccp-staging-2 --approve 
2022-05-31 09:12:48 [ℹ]  skipped existing "kube-system:ServiceAccount/aws-node"
2022-05-31 09:12:48 [ℹ]  replaced "CustomResourceDefinition.apiextensions.k8s.io/eniconfigs.crd.k8s.amazonaws.com"
2022-05-31 09:12:48 [ℹ]  replaced "ClusterRole.rbac.authorization.k8s.io/aws-node"
2022-05-31 09:12:48 [ℹ]  replaced "ClusterRoleBinding.rbac.authorization.k8s.io/aws-node"
2022-05-31 09:12:48 [ℹ]  replaced "kube-system:DaemonSet.apps/aws-node"
2022-05-31 09:12:48 [ℹ]  "aws-node" is now up-to-date

k get ds aws-node -n kube-system -o wide 
NAME       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE    CONTAINERS   IMAGES                                                                   SELECTOR
aws-node   49        49        49      49           49          <none>          179d   aws-node     602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.11.0   k8s-app=aws-node
```

**Comment by Skarlso** [comment]
@steveizzle Neat! Thank you Steve! :)

**Comment by Skarlso** [comment]
Hmm, I wonder what this does to existing clusters and addons.

**Comment by Skarlso** [comment]
Also, @steveizzle let's test this with an IPv6 cluster. Because if we install this by default I think our current networking implementation might break? Since we have to enable that environment setting:

```yaml
          - name: ENABLE_IPv6
            value: "false"
```

**Comment by steveizzle** [comment]
Ok, then i am maybe wrong. Will double check that

**Comment by Skarlso** [comment]
We will actually be upgrading the aws-node ourselves with this issue: https://github.com/weaveworks/eksctl/issues/4477

Closing this PR for now since it will be superseded by that work. However, we will link back to https://github.com/weaveworks/eksctl/issues/5336 to make sure that problem will also be fixed. Cheers!

**Comment by steveizzle** [comment]
Works for me ☺️

**Pull request closed without merging**
