### PR TITLE
Make Kubernetes 1.23 the default

### LINKED ISSUE #5607: [Task] Make EKS 1.23 the default
After EKS 1.23 is out and made the default in the EKS console, eksctl should switch to EKS 1.23 as the default version. 

Reference PR: https://github.com/weaveworks/eksctl/pull/5136

### PR DESCRIPTION
**Pull request by TiberiuGC**
### Description

Closes #5607 

Trimmed CLI output of creating a cluster on the new version

```
2022-08-18 10:50:08 [ℹ]  eksctl version 0.110.0-dev+1a73c2b2.2022-08-18T10:42:08Z
2022-08-18 10:50:09 [ℹ]  using Kubernetes version 1.23
2022-08-18 10:50:09 [ℹ]  creating EKS cluster "cluster-1" in "eu-north-1" region with un-managed nodes
2022-08-18 10:50:09 [ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "cluster-1" in "eu-north-1"
2022-08-18 10:50:09 [ℹ]  
2 sequential tasks: { create cluster control plane "cluster-1", 
    2 sequential sub-tasks: { 
        wait for control plane to become ready,
        create nodegroup "ng-1",
    } 
}
2022-08-18 11:06:53 [ℹ]  waiting for the control plane availability...
2022-08-18 11:06:53 [✔]  saved kubeconfig as "/Users/tiberiu-weave/.kube/config"
2022-08-18 11:08:01 [ℹ]  nodegroup "ng-1" has 1 node(s)
2022-08-18 11:08:01 [ℹ]  node "ip-192-168-93-174.eu-north-1.compute.internal" is ready
2022-08-18 11:08:02 [✔]  EKS cluster "cluster-1" in "eu-north-1" region is ready
```

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by cPu1 — APPROVED** [review]
LGTM. We'll have to hold off merging until the EKS Console has made 1.23 the default. 

We should also monitor the integration tests after merging to ensure we aren't relying on 1.22 as the default anywhere.

**Comment by ejsmith** [comment]
Getting the following error trying to update core-dns on a 1.23 cluster with the rc.0 release.

```sh
eksctl utils update-coredns --cluster my-cluster
Error: open assets/coredns-1.23.json: file does not exist
```

**Comment by Himangini** [comment]
> Getting the following error trying to update core-dns on a 1.23 cluster with the rc.0 release.
> 
> ```shell
> eksctl utils update-coredns --cluster my-cluster
> Error: open assets/coredns-1.23.json: file does not exist
> ```

answered in original PR

**Review by Himangini — APPROVED** [review]
👍🏻

**Comment by Himangini** [comment]
Merge this PR after 21st September.

**Comment by cPu1** [comment]
EKS 1.23 is not the default yet, so we'll have to wait a bit more before merging.

**Comment by cPu1** [comment]
> EKS 1.23 is not the default yet, so we'll have to wait a bit more before merging.

EKS 1.23 is now the default. This PR is good to merge.

**Pull request merged**
