### PR TITLE
Fix slack notification syntax

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Fixes https://github.com/weaveworks/eksctl/issues/5027

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by aclevername — CHANGES_REQUESTED** [review]
I'm 99% sure that `if: success()` is valid :thinking:

**Comment by Skarlso** [comment]
>I'm 99% sure that if: success() is valid 🤔

I'm 99% sure it's not. :D It's a context. https://docs.github.com/en/actions/learn-github-actions/contexts#job-status-check-functions

Also observe: https://github.com/weaveworks/eksctl-ci/blob/main/.github/workflows/integration-tests.yaml#L85

**Comment by Skarlso** [comment]
Further, observe the sample on Github doc:

```yaml
name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with logs
        run: |
          mkdir ${{ runner.temp }}/build_logs
          ./build.sh --log-path ${{ runner.temp }}/build_logs
      - name: Upload logs on fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Build failure logs
          path: ${{ runner.temp }}/build_logs
```

**Comment by Skarlso** [comment]
@aclevername Nice spot on the subflow thing. Thanks. :)

**Comment by aclevername** [comment]
can we get another copy of this merged into the 0.91.0-rc.0 release branch, so it gets applied when we promote that release?

**Comment by Skarlso** [comment]
> can we get another copy of this merged into the 0.91.0-rc.0 release branch, so it gets applied when we promote that release?

Wouldn't it just be applied once 0.92.0 is released anyways?

**Comment by aclevername** [comment]
> > can we get another copy of this merged into the 0.91.0-rc.0 release branch, so it gets applied when we promote that release?
> 
> Wouldn't it just be applied once 0.92.0 is released anyways?

yeah true. I think getting the docs fix in is more important

**Review by Himangini — APPROVED** [review]
👍🏻

**Pull request merged**
