### PR TITLE
Enable create iamidentitymapping in AWS CN partition

### PR DESCRIPTION
**Pull request by lamricky0**
### Description

This is a fix for [ISSUE-4162](https://github.com/weaveworks/eksctl/issues/4162) in create iamidentitymapping when it is called in a AWS region that is in a different AWS partition other than aws like aws-cn.

### Testing
```
./eksctl create iamidentitymapping \
>     --cluster lamricky-test2 \
>     --namespace lamricky-test-ns \
>     --service-name "emr-containers"
2021-09-15 15:07:04 [ℹ]  eksctl version 0.65.0-dev+20d207dc.2021-09-15T13:50:03Z
2021-09-15 15:07:04 [ℹ]  using region cn-north-1
2021-09-15 15:07:09 [ℹ]  replaced "lamricky-test-ns:Role.rbac.authorization.k8s.io/emr-containers"
2021-09-15 15:07:10 [ℹ]  replaced "lamricky-test-ns:RoleBinding.rbac.authorization.k8s.io/emr-containers"
2021-09-15 15:07:10 [ℹ]  adding identity "arn:aws-cn:iam::065596917820:role/AWSServiceRoleForAmazonEMRContainers" to auth ConfigMap
88665a3771a7:eksctl lamricky$ kubectl describe configmaps aws-auth --namespace kube-system
Name:         aws-auth
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
mapUsers:
----
[]

mapRoles:
----
- groups:
  - system:bootstrappers
  - system:nodes
  rolearn: arn:aws-cn:iam::065596917820:role/eksctl-lamricky-test2-nodegroup-n-NodeInstanceRole-1QBIWKB2R2UHN
  username: system:node:{{EC2PrivateDNSName}}
- rolearn: arn:aws-cn:iam::065596917820:role/AWSServiceRoleForAmazonEMRContainers
  username: emr-containers
```

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by cPu1 — COMMENTED** [review]
The changes look good to me, but we do not have access to China regions to test it. 

@walkley are you able to test this PR?

**Comment by lamricky0** [comment]
> The changes look good to me, but we do not have access to China regions to test it.
> 
> @walkley are you able to test this PR?

I tested this against a AWS account in China. 065596917820 is a Chinese AWS account. You can see that create iamidentitymapping added _arn:**aws-cn**:iam::065596917820:role/AWSServiceRoleForAmazonEMRContainers_ instead of _arn:**aws**:iam::065596917820:role/AWSServiceRoleForAmazonEMRContainers_

**Comment by cPu1** [comment]
> > The changes look good to me, but we do not have access to China regions to test it.
> > @walkley are you able to test this PR?
> 
> I tested this against a AWS account in China. 065596917820 is a Chinese AWS account. You can see that create iamidentitymapping added _arn:**aws-cn**:iam::065596917820:role/AWSServiceRoleForAmazonEMRContainers_ instead of _arn:**aws**:iam::065596917820:role/AWSServiceRoleForAmazonEMRContainers_

I did notice that you tested the command and the aws-auth ConfigMap gets updated with the correct ARN. I was more referring to testing this with EMR Containers. It'd be great if you're able to confirm that, otherwise I'd like to wait for @walkley to confirm before merging.

**Review by aclevername — APPROVED** [review]
LGTM! Thanks for the PR :sparkles:

**Comment by nithu0115** [comment]
I built an eksctl binary from this PR and tested in cn-northwest-1 region and was able to successfully start a job. 
https://gist.github.com/nithu0115/bd46d59509637b90e297c9b4b6ec5e77

**Comment by cPu1** [comment]
> I built an eksctl binary from this PR and tested in cn-northwest-1 region and was able to successfully start a job. https://gist.github.com/nithu0115/bd46d59509637b90e297c9b4b6ec5e77
> 
> PR LGTM :shipit:

Great, thanks for helping out!

**Pull request merged**
