### PR TITLE
Upgrade spf13/cobra to v1.1.0 to fix zsh completion issue

### LINKED ISSUE #2747: zsh autocomplete error when calling eksctl create nodegroup - invalid option definition
**What happened?**
When I type `eksctl create nodegroup [TAB]`
It shows following error
`_arguments:comparguments:319: invalid option definition: --version[Kubernetes version (valid options: 1.14, 1.15, 1.16, 1.17) [for nodegroups "auto" and "latest" can be used to automatically inherit version from the control plane or force latest]]:
`

Tested on my two macbook pro / Amazon Linux 2 EC2 Instance and saw the same error.

**What you expected to happen?**
Showing the autocomplete choices without any error.

**How to reproduce it?**
1. follow the guide to install eksctl autocompletion
https://eksctl.io/introduction/#zsh
2. using zsh and type
`eksctl create nodegroup [TAB]`

**Anything else we need to know?**
I think it's similar to this issue:
https://github.com/clap-rs/clap/issues/771
I can manually add escape character to ~/.zsh/completion/_eksctl line334
圖片
After that, it works fine
圖片

**Versions**
```
$ eksctl version
0.29.2
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
圖片

### PR DESCRIPTION
**Pull request by ysam12345**
### Description

Upgrade version of spf13/cobra from v1.0.0 to v1.1.0 to fix #2747

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [ ] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Review by michaelbeaumont — APPROVED** [review]

**Comment by michaelbeaumont** [comment]
Thanks!

**Comment by michaelbeaumont** [comment]
It looks like the tests that check CLI output are failing. This is likely because the output has changed somehow between versions

**Comment by ysam12345** [comment]
> It looks like the tests that check CLI output are failing. This is likely because the output has changed somehow between versions

Ok, I'll look into it.

**Comment by ysam12345** [comment]
@michaelbeaumont I found that is because RP https://github.com/spf13/cobra/pull/894 changed some error output from stdOut to stdErr, so some of our test cases failed. I can fix it by adding stdErr to our output buffer, and all the test cases passed. 
image
But I don't think this is the best practice, so I'll take some time to rewrite some code of unit test to fit the new spf13/cobra module.

**Comment by ysam12345** [comment]
Need more discuss in https://github.com/weaveworks/eksctl/issues/2747.

**Pull request closed without merging**
