### PR TITLE
Add well-known IAM Role Service Account policy for the EBS CSI driver

### PR DESCRIPTION
**Pull request by jalaziz**
### Description

Add well-known IAM policy support for EBS CSI driver/controller IAM role
service accounts.

The EBS CSI driver is a common installation that should probably be supported by a well-known policy.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Callisto13** [comment]
Thanks for this @jalaziz 👍 .

Just thinking, I am not sure we have docs for this `wellKnownPolicies` thing 🤔 . Do you think you could add some listing options people have?

**Comment by jalaziz** [comment]
> Thanks for this @jalaziz 👍 .
> 
> Just thinking, I am not sure we have docs for this `wellKnownPolicies` thing 🤔 . Do you think you could add some listing the options people have?

Was thinking the same thing actually. Will add some docs.

**Comment by jalaziz** [comment]
@Callisto13 Turns out there were docs, it was just very subtle.

I've tried to improve the docs a bit.

**Comment by jalaziz** [comment]
@Callisto13 anything else to improve with this PR?

**Comment by Callisto13** [comment]
hey @jalaziz thanks for your patience: we were having a little existential crisis on the `wellKnownPolicies` feature, but all good now 😂

**Review by Callisto13 — APPROVED** [review]
lgtm 🎉

**Pull request merged**
