### PR TITLE
Remove --profile as incompatible flag with --dry-run

### PR DESCRIPTION
**Pull request by rongshengfang**
### Description

This is to address issue/bug #6167 where the following error message would appear when `--profile` is specified along with `--dry-run` for the `eksctl create nodegroup` subcmmand:

```
Error: couldn't create node group filter from command line options: cannot use --profile with --dry-run as this option cannot be represented in ClusterConfig
```

`--profile` (in the absense of `AWS_PROFILE` environment variable) is required for the `create` subcommand to produce the dry-run output as `eksctl` will need to connect to AWS and retrieve info about the resource it's trying to create in dry-run mode.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by cPu1** [comment]
@rongshengfang, I have left a [comment](https://github.com/weaveworks/eksctl/issues/6167#issuecomment-1423987785) in the issue explaining why `--profile` isn't allowed with `--dry-run`.

**Comment by Himangini** [comment]
Can we close this PR?

**Comment by rongshengfang** [comment]
> Can we close this PR?

@Himangini I responded [here](https://github.com/weaveworks/eksctl/issues/6167#issuecomment-1424412479), but I haven't seen any response to it before bug #6167 was closed.

**Comment by cPu1** [comment]
> > Can we close this PR?
> 
> @Himangini I responded [here](https://github.com/weaveworks/eksctl/issues/6167#issuecomment-1424412479), but I haven't seen any response to it before bug #6167 was closed.

I have responded to your comment: https://github.com/weaveworks/eksctl/issues/6167#issuecomment-1455703770

**Pull request closed without merging**
