### PR TITLE
Fixed the transitive dependency for opencensus-proto

### PR DESCRIPTION
**Pull request by sayboras**
### Description
To fix the go 1.13 compilation issue due to transitive dependency version. https://github.com/weaveworks/eksctl/issues/1388

The go version in circle ci is still with 1.12, i leave it as it is right now. 
Changes are testing manually

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [ ] Added tests that cover your change (if possible)
- [x] All unit tests passing (i.e. `make test`)
- [ ] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [x] Manually tested

### CODE REVIEW

**Comment by martina-if** [comment]
Hi @sayboras , can you add some instructions on how you have tested this manually and add the output too? This will help us do the last bit of testing when we release.

**Comment by sayboras** [comment]
@martina-if sure, please find below the output of testing. I provisioned a new cluster with my own AWS account.

```
$ go version
go version go1.13.1 darwin/amd64
$ make build
env GOBIN=/Users/tammach/go/bin time go generate ./pkg/nodebootstrap
        2.42 real         1.50 user         0.99 sys
time go mod download k8s.io/code-generator # make sure the code-generator is present

real	0m0.111s
user	0m0.209s
sys	0m0.127s
time env GOPATH="$(go env GOPATH)" bash "$(go env GOPATH)/pkg/mod/k8s.io/code-generator@v0.0.0-20190808180452-d0071a119380/generate-groups.sh" \
	  deepcopy,defaulter _ ./pkg/apis eksctl.io:v1alpha5 --go-header-file .license-header --output-base="/Users/tammach/go/src/github.com/weaveworks/eksctl" \
	  || (cat codegenheader.txt ; cat pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go; exit 1)
Generating deepcopy funcs

real	0m26.925s
user	0m54.240s
sys	0m40.773s
CGO_ENABLED=0 time go build -ldflags "-X github.com/weaveworks/eksctl/pkg/version.gitCommit=0.2.0-478-gb3b3be48 -X github.com/weaveworks/eksctl/pkg/version.builtAt=1570139532" ./cmd/eksctl
       15.25 real        20.42 user         6.71 sys
$ ./eksctl version
[ℹ]  version.Info{BuiltAt:"1570139532", GitCommit:"0.2.0-478-gb3b3be48", GitTag:""}
```
Running create cluster command

```
$ eksctl create cluster \
  --name ${CLUSTER_NAME} \
  --nodegroup-name standard-workers \
  --node-type m4.large \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --node-ami auto \
  --vpc-private-subnets "${VPC_PRIVATE_SUBNETS}" \
  --vpc-public-subnets "${VPC_PUBLIC_SUBNETS}"
[ℹ]  using region ap-southeast-2
[✔]  using existing VPC (vpc-0d2c525c13e574a83) and subnets (private:[subnet-0418501570300fd72 subnet-05038ca5660fb3b51 subnet-0557c41d077b13b61] public:[subnet-00a9541d32ac5b751 subnet-0bb3f34e36c86fdfa subnet-0df9f31074d51cfdb])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  nodegroup "standard-workers" will use "ami-0f4f8678ca910061a" [AmazonLinux2/1.13]
[ℹ]  using Kubernetes version 1.13
[ℹ]  creating EKS cluster "sandbox-2" in "ap-southeast-2" region
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=ap-southeast-2 --name=sandbox-2'
[ℹ]  CloudWatch logging will not be enabled for cluster "sandbox-2" in "ap-southeast-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=ap-southeast-2 --name=sandbox-2'
[ℹ]  2 sequential tasks: { create cluster control plane "sandbox-2", create nodegroup "standard-workers" }
[ℹ]  building cluster stack "eksctl-sandbox-2-cluster"
[ℹ]  deploying stack "eksctl-sandbox-2-cluster"
...
```

**Comment by stefanprodan** [comment]
I can confirm that this builds and runs ok for me but there is an indirect that's not suppose to be there (comes from #1389)

```diff
diff --git a/go.mod b/go.mod
index fa5dcfbb..9d521c67 100644
--- a/go.mod
+++ b/go.mod
@@ -25,7 +25,6 @@ require (
        github.com/fluxcd/flux v1.15.0
        github.com/fluxcd/helm-operator v1.0.0-rc2
        github.com/go-ini/ini v1.37.0 // indirect
-       github.com/go-stack/stack v1.8.0 // indirect
        github.com/gobuffalo/envy v1.7.0 // indirect
        github.com/gobwas/glob v0.2.3
        github.com/gofrs/flock v0.7.1 // indirect
```

**Comment by sayboras** [comment]
@cPu1 @stefanprodan you are right, I have incorporated your review comments. Please help to have another look

**Comment by stefanprodan** [comment]
Running `go mod tidy` on the latest commit results in:
```diff
diff --git a/go.mod b/go.mod
index 1ee4dfcd..ed2af9e1 100644
--- a/go.mod
+++ b/go.mod
@@ -9,7 +9,6 @@ require (
        github.com/aws/aws-sdk-go v1.23.15
        github.com/awslabs/goformation v0.0.0-20190320125420-ac0a17860cf1
        github.com/blang/semver v3.5.1+incompatible
-       github.com/census-instrumentation/opencensus-proto v0.2.1 // indirect
        github.com/christopherhein/go-version v0.0.0-20180807222509-fee8dd1f7c24
        github.com/cloudflare/cfssl v0.0.0-20190726000631-633726f6bcb7
        github.com/coredns/coredns v0.0.0-20170910182647-1b60688dc8f7 // indirect
diff --git a/go.sum b/go.sum
index b446820a..96c3a0f1 100644
--- a/go.sum
+++ b/go.sum
@@ -157,12 +157,9 @@ github.com/campoy/unique v0.0.0-20180121183637-88950e537e7e/go.mod h1:9IOqJGCPMS
 github.com/cenkalti/backoff v2.0.0+incompatible/go.mod h1:90ReRw6GdpyfrHakVjL/QHaoyV4aDUVVkXQJJJ3NXXM=
 github.com/cenkalti/backoff v2.1.1+incompatible/go.mod h1:90ReRw6GdpyfrHakVjL/QHaoyV4aDUVVkXQJJJ3NXXM=
 github.com/census-instrumentation/opencensus-proto v0.0.3-0.20181214143942-ba49f56771b8/go.mod h1:f6KPmirojxKA12rnyqOA5BBL4O983OfeGPqjHWSTneU=
-github.com/census-instrumentation/opencensus-proto v0.1.0-0.20181214143942-ba49f56771b8/go.mod h1:f6KPmirojxKA12rnyqOA5BBL4O983OfeGPqjHWSTneU=
 github.com/census-instrumentation/opencensus-proto v0.1.0/go.mod h1:f6KPmirojxKA12rnyqOA5BBL4O983OfeGPqjHWSTneU=
 github.com/census-instrumentation/opencensus-proto v0.2.0 h1:LzQXZOgg4CQfE6bFvXGM30YZL1WW/M337pXml+GrcZ4=
 github.com/census-instrumentation/opencensus-proto v0.2.0/go.mod h1:f6KPmirojxKA12rnyqOA5BBL4O983OfeGPqjHWSTneU=
-github.com/census-instrumentation/opencensus-proto v0.2.1 h1:glEXhBS5PSLLv4IXzLA5yPRVX4bilULVyxxbrfOtDAk=
-github.com/census-instrumentation/opencensus-proto v0.2.1/go.mod h1:f6KPmirojxKA12rnyqOA5BBL4O983OfeGPqjHWSTneU=
 github.com/centrify/cloud-golang-sdk v0.0.0-20180119173102-7c97cc6fde16/go.mod h1:C0rtzmGXgN78pYR0tGJFhtHgkbAs0lIbHwkB81VxDQE=
 github.com/cespare/xxhash v1.1.0/go.mod h1:XrSqR1VqqWfGrhpAt58auRo0WTKS1nRRg3ghfAqPWnc=
 github.com/chaseadamsio/goorgeous v1.1.0 h1:J9UrYDhzucUMHXsCKG+kICvpR5dT1cqZdVFTYvSlUBk=
```

**Comment by sayboras** [comment]
@stefanprodan sorry, I missed `git push` after re-run `go mod tidy`, hope that it's fine now.

**Comment by stefanprodan** [comment]
No worries, we should be running `go mod tidy` and break the build on `git diff`.

**Comment by martina-if** [comment]
Hi @sayboras can you do a final rebase? then I can approve and merge right away

**Comment by sayboras** [comment]
@martina-if it should be ready to merge now. Thanks 💯

**Comment by martina-if** [comment]
Fixes #1388

**Pull request merged**
