### PR TITLE
Add support for Sao Paulo sa-east-1

### PR DESCRIPTION
**Pull request by sayboras**
### Description

Add support for sa-east-1 https://github.com/weaveworks/eksctl/issues/1398

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [ ] Added tests that cover your change (if possible)
- [x] All unit tests passing (i.e. `make test`)
- [ ] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [ ] Manually tested

### CODE REVIEW

**Comment by sayboras** [comment]
I created `Draft pull request` to prevent merging, we will wait until it's officially supported.

**Comment by martina-if** [comment]
Thanks @sayboras !

**Comment by martina-if** [comment]
Hey @sayboras we would like to merge this soon, can you please rebase and fix the conflicts?

**Comment by sayboras** [comment]
@martina-if it's done now 👍

**Comment by martina-if** [comment]
closes #1398

**Pull request merged**
