### PR TITLE
Treat p4d as a GPU instance

### PR DESCRIPTION
**Pull request by samsamoa**
### Description

p4d instances have GPUs: https://aws.amazon.com/ec2/instance-types/p4/
This change makes the AMI resolve properly

### Checklist
- [x] Manually tested
- [x] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [ ] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by Callisto13** [comment]
Thanks @samsamoa !

Could you put each `HasStrings` section on a new line (similar to `IsARMInstanceType` above) for easy readability?

**Comment by samsamoa** [comment]
Sure - just made that fix.

**Review by Callisto13 — APPROVED** [review]
LGTM 👍

**Comment by g-karthik** [comment]
@samsamoa interesting, good to know OpenAI uses `eksctl`! :)

**Pull request merged**
