### PR TITLE
Mark EKS 1.13 as deprecated

### PR DESCRIPTION
**Pull request by sayboras**
### Description

Fixes https://github.com/weaveworks/eksctl/issues/2141

Created as draft PR, so that there will be no notification. Will send to review closing to 30th June.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by sayboras** [comment]
> Merge before Friday 26th so it's released with 0.23.0

Thanks, let me set reminder for myself in slack :+1:

**Comment by martina-if** [comment]
@sayboras I think we can already merge this since 0.22.0 was already branched out. Can you please rebase it? :)

**Comment by sayboras** [comment]
> I think we can already merge this since 0.22.0 was already branched out. Can you please rebase it? :)

@martina-if Done :100:

**Comment by martina-if** [comment]
Manually tested and it works well :+1: 

```
./eksctl create cluster -f examples/01-simple-cluster.yaml 
[ℹ]  eksctl version 0.23.0-dev+8715a769.2020-06-18T14:57:51Z
[ℹ]  using region eu-north-1
Error: invalid version, 1.13 is no longer supported, supported values: 1.14, 1.15, 1.16
see also: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
```

```
./eksctl create cluster --name martina-test-1-13-3 --version 1.13
[ℹ]  eksctl version 0.23.0-dev+8715a769.2020-06-18T14:57:51Z
[ℹ]  using region eu-north-1
Error: invalid version, 1.13 is no longer supported, supported values: 1.14, 1.15, 1.16
see also: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
```

**Pull request merged**
