### PR TITLE
Add option to add IAM policies for AWS ALB Ingress Controller

### PR DESCRIPTION
**Pull request by mcfedr**
### Description

The [AWS ALB Ingress Controller](https://github.com/kubernetes-sigs/aws-alb-ingress-controller) is a very useful part of any EKS stack, and so it would be very nice to be able to add its required policies automatically along with the others eksctl can add

### Checklist

- [X] Code compiles correctly (i.e `make build`)
- [X] Added tests that cover your change (if possible)
- [X] All unit tests passing (i.e. `make test`)
- [X] All integration tests passing (i.e. `make integration-test`)
- [X] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [X] Added yourself to the `humans.txt` file

### CODE REVIEW

**Comment by errordeveloper** [comment]
Thanks, this was a long awaited one!

**Comment by christopherhein** [comment]
@M00nF1sh can you take a look at this as well?

**Comment by errordeveloper** [comment]
xref #53

**Pull request merged**
