### PR TITLE
Add support for EKS 1.22

### PR DESCRIPTION
**Pull request by aclevername**
### Description
Closes https://github.com/weaveworks/eksctl-private/issues/394

Add support for k8s 1.22

Breaking changes https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes none of them affect us- we have some references to some of the legacy API versions, e.g. `apiextensions.k8s.io/v1beta` and `certificates.k8s.io/v1beta1` but they are only used for the `vpc-admission` controller, which isn't required on newer versions of EKS (@cPu1 to confirm :smile: )

TODO:
- test unmanaged nodegroups
- green integration test run

### CODE REVIEW

**Review by Skarlso — APPROVED** [review]

**Review by nikimanoledaki — APPROVED** [review]

**Comment by cPu1** [comment]
>they are only used for the vpc-admission controller, which isn't required on newer versions of EKS (@cPu1 to confirm smile )

Correct.

**Comment by aclevername** [comment]
@Himangini did you mean to add the `breaking` label? I don't think this PR is a breaking change

**Review by Himangini — COMMENTED** [review]
Please link the Issue ticket in the description.

**Comment by toabctl** [comment]
EKS 1.22 is available now. please merge & create a new release.

**Pull request merged**
