### PR TITLE
update to core-dns:1.6.6

### PR DESCRIPTION
**Pull request by ajayk**
### Description
- bump image to 940911992744.dkr.ecr.us-west-2.amazonaws.com/eks/coredns:v1.6.6
- change proxy to forward 
- more details can be found at  https://docs.aws.amazon.com/eks/latest/userguide/coredns.html

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`) and target version (e.g. `version/0.12.0`)
- [ ] Added note in `docs/release_notes/draft.md` (or relevant release note)

### CODE REVIEW

**Comment by stefanprodan** [comment]
@ajayk the AWS docs say:
> If your current version is earlier than 1.5.0, then you need to modify the config map for coredns to use the forward plug-in, rather than the proxy plug-in.

My understanding is that for CoreDNS 1.6.6 we should be using the `proxy` plug-in.

**Comment by ajayk** [comment]
@stefanprodan  the documentation wording is little misleading if anything less than 1.5.0(coredns) we should change the proxy to forward 

please see the latest coredns  `https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2019-11-15/dns.yaml`

it has version 1.6.6 and the `forward`

**Comment by stefanprodan** [comment]
@ajayk thanks for that link, it's all clear to me now.

**Comment by martina-if** [comment]
@ajayk Can you please rebase your change so I can merge it?

**Comment by ajayk** [comment]
@martina-if : done

**Pull request merged**
