### PR TITLE
Update AWS VPC CNI to 1.5.4

### LINKED ISSUE #1376: Update AWS VPC CNI Plugin to 1.5.4
https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.5.4/config/v1.5/aws-k8s-cni.yaml#L84

`1.5.4` is also required to support `g4dn` instances.

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Closes #1376 

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [x] Added tests that cover your change (if possible)
- [x] All unit tests passing (i.e. `make test`)

<sub><sup>Minor typo in the branch name: *update-aws-ani-1376* -> *update-aws-cni-1376*</sub></sup>

### CODE REVIEW

**Comment by martina-if** [comment]
Have you tested it manually?

**Comment by cPu1** [comment]
@martina-if not with eksctl. I was testing out g4dn instances and the aws-node pod, which was on 1.5.3 kept crashing. Upgrading the container image to 1.5.4 resolved the issue.

**Comment by buzzsurfr** [comment]
Support for g4dn instances was added to CNI version 1.5.4, which is why it broke beforehand.

**Comment by martina-if** [comment]
@cPu1 I think you can test it with `eksctl utils update-aws-node` just to see that the new container replaces the old one and it starts correctly.

**Comment by buzzsurfr** [comment]
This pulls the right CNI, but the AMIs are out of date. There's already a similar PR #1362 to fix that (which also needs an update), so we should either combine or merge both, or drop #1362 and start a new PR.

**Comment by cPu1** [comment]
>Support for g4dn instances was added to CNI version 1.5.4, which is why it broke beforehand.\

>This pulls the right CNI, but the AMIs are out of date. There's already a similar PR #1362 to fix that (which also needs an update), so we should either combine or merge both, or drop #1362 and start a new PR.

I'm familiar with that PR. This change was made to fix the issues in that PR.

>@cPu1 I think you can test it with eksctl utils update-aws-node just to see that the new container replaces the old one and it starts correctly.

That works. I was concerned that the old/existing worker node AMIs may not work with the newer CNI version, but looks like it does.

**Comment by marccarre** [comment]
Related to #1344 and #1362.

**Pull request merged**
