### PR TITLE
Error early for unmanaged nodegroup using ARM GPU instance type

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Deals with https://github.com/weaveworks/eksctl/issues/4865.

This is the fail early part for unmanaged nodegroups.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by Himangini — APPROVED** [review]

**Review by nikimanoledaki — APPROVED** [review]
LGTM! 👍

**Review by cPu1 — APPROVED** [review]
LGTM.

Can we add another test case for when `ng.InstanceType` is set to an ARM-GPU instance type?

```golang
ng.InstanceType = "r6g.medium"
ng.AMIFamily = api.NodeImageFamilyAmazonLinux2
err := api.ValidateNodeGroup(0, ng)
Expect(err).To(MatchError("ARM GPU instance types are not supported for unmanaged nodegroups with AMIFamily AmazonLinux2"))
```

**Comment by Legion2** [comment]
I cannot find any documentation that states that `r6g` is an ARM GPU instance, we use the `r6g` instances and they don't have a GPU. Now we cannot use eksctl anymore because of the error `Error: ARM GPU instance types are not supported for unmanaged nodegroups with AMIFamily`.

**Comment by Skarlso** [comment]
@Legion2 

Hello.

Interesting. I give you that, that it's not easy to find these things from AWS. :/

I believe there was a blog post that detailed instance types. R6g was marked as graviton GPU instance. 

For example this blog post here https://aws.amazon.com/blogs/machine-learning/aws-and-nvidia-to-bring-arm-based-instances-with-gpus-to-the-cloud/ details that these Graviton 2 instance types are now offered with GPU acceleration. 

Granted, it doesn't really detail if it's opt-in or opt-out or what...

I'll try to get to the bottom of this and figure out if these instance types are GPU chipped or not now.

In the meantime, please open a ticket and ping me in it so I can track this. Thanks.

**Pull request merged**
