### PR TITLE
Switch admissionregistration and certificates API to v1

### LINKED ISSUE #3873: Deprecated apiVersion used for MutatingWebhookConfiguration and CertificateSigningRequest
Hello, when creating a new admission controller, eksctl prints out the following warnings:
```
warnings.go:67] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
```

```
warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
```

This can be reproduced following the instructions here\:
https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support

**VERSIONS**

```
Admin:~/environment $ eksctl version
0.53.0
Admin:~/environment $ kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:13:28Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by aledbf**
### Description

Fixes #3873

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [X] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by aclevername** [comment]
Thanks for the PR @aledbf! The changes look good, but I'm concerned about backwards compatibility. Do these changes prevent the functionality from working against  clusters older than 1.19? I believe the `v1` API only came out in 1.19. I think we might have to maintain the two codepaths, like we do for cleaning up ingresses https://github.com/weaveworks/eksctl/blob/4e7db646543867ee8d145be22895d518ed88eef9/pkg/elb/ingress.go

**Comment by aledbf** [comment]
@aclevername good question

[admissionregistration.k8s.io/v1](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#prerequisites) is available since v1.16

but [certificates/v1](https://github.com/kubernetes/api/commit/fb638f044be02c538bd9e52a8cf43c28e9c1486b#diff-38ad7dbce36e86026ad3f3632cfd0f0e32db9fa7f33b13b46f8a69e8a55809f1) requires v1.19

**Comment by aclevername** [comment]
> [admissionregistration.k8s.io/v1](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#prerequisites) is available since v1.16 but [certificates/v1](https://github.com/kubernetes/api/commit/fb638f044be02c538bd9e52a8cf43c28e9c1486b#diff-38ad7dbce36e86026ad3f3632cfd0f0e32db9fa7f33b13b46f8a69e8a55809f1) requires v1.19

good spot! I guess we can go ahead with the `admission` changes, and have two codepaths for the `certificate` :smile:

**Comment by Callisto13** [comment]
Hey @aledbf, just checking on the status of this. Do you plan to finish (adding the 16-18 codepath) or would you like us to take over? We'd like to get this out in the next release 😄

**Comment by aledbf** [comment]
@Callisto13 I can't continue until next week. It would be great if you could take this over

**Comment by cPu1** [comment]
> @Callisto13 I can't continue until next week. It would be great if you could take this over. Apologies for that

No worries, someone from the team will take this over.

**Comment by Callisto13** [comment]
Closing this while we re-assign. Reopen if decision is made to continue with this approach

**Pull request closed without merging**
