### PR TITLE
Support for offline build and test

### PR DESCRIPTION
**Pull request by d-luu**
There are files used in the build/test to go generate that make
calls to retrieve files from online resources.
This change would allow using artifacts already downloaded.

Artifacts needed:
- pkg/nodebootstrap/maxpods.go
- pkg/addons/default/assets/aws-node.yaml
    
Usage:
export EKSCTL_BUILD_OFFLINE=true

Note that when submitting a PR, you should unset the environment
variables so that you can get the latest files.

Issue #1608

### Checklist
- [ ] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [x] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`) and target version (e.g. `version/0.12.0`)
- [ ] Added note in `docs/release_notes/draft.md` (or relevant release note)

### CODE REVIEW

**Comment by martina-if** [comment]
Hi @d-luu , thank you for contributing to eksctl :)

I checked the PR and although it's a good idea I think we should solve this in a different way.

eksctl has many build time dependencies. Some of these are generated code (which doesn't need any connection to the internet) and others are more of a "downloading" operation.

What I would like to have is a way to separate these two kinds of resources so that the generated code is always generated when we run `make build` but the resources that are downloaded from the internet are only updated when we want to do that (for example, with a `make upgrade-assets` or similarly named command). This would also help having reproducible build under our control.

Would you like to work on that?

**Comment by d-luu** [comment]
@martina-if I can make the changes you requested

**Comment by d-luu** [comment]
@martina-if I have updated the makefile to include a download-assets rule

I have also added a conditional in the generate where if any files are missing it will try and download them (I was going to try this using the `wildcard` function with `ifeq` but the shell conditionally was cleaner in my opinion)...this was done so that it doesnt break current build processes

**Comment by martina-if** [comment]
Superseded by https://github.com/weaveworks/eksctl/pull/2039

**Pull request closed without merging**
