### PR TITLE
Fix netlify.toml publish path

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Description

I don't understand why this worked previously?

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by cPu1 — APPROVED** [review]

**Comment by morancj** [comment]
> I don't understand why this worked previously?

Re-linking the repo on Netlify caused the duplication of userdocs in the output path (i.e. `userdocs/userdocs/site`). I fixed in the UI, missed here: apologies! :bow:

**Comment by dholbach** [comment]
> I don't understand why this worked previously?

```
3:37:28 PM: Different build dir detected, going to use the one specified in the Netlify configuration file: 'userdocs' versus '/userdocs' in the Netlify UI
3:37:28 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'userdocs/site' versus 'site' in the Netlify UI
3:37:28 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'cd .. && make -f Makefile.docs build-pages' versus 'cd .. && make build-pages' in the Netlify UI
```

**Comment by dholbach** [comment]
^ This is from current `main` build.

**Comment by morancj** [comment]
Yes, we should note the current BUI Netlify config just in case, then remove, so the TOML is the obvious source of truth.

**Comment by michaelbeaumont** [comment]
Ah ok, so before the relinking, the `public` path didn't prepend `base`?

**Comment by morancj** [comment]
> Ah ok, so before the relinking, the `publish` path didn't prepend `base`?

Exactly!

**Pull request merged**
