### PR TITLE
Propagate user defined tags to instance and volumes in EKS nodes

### PR DESCRIPTION
**Pull request by saleem-mirza**
### Description
Currently, `eksctl` does not support propagating user defined tags to underlaying instances and ebs volumes in managed and un-managed nodes

Add support to inject user defined tags to underlaying compute resources.

#### Changes
refactored `makeTags` function in managed_launch_template.go to add `volume`, `elastic-gpu`, and `spot-instances-request`

```go
	var launchTemplateTagSpecs []gfnec2.LaunchTemplate_TagSpecification

	launchTemplateTagSpecs = append(launchTemplateTagSpecs,
		gfnec2.LaunchTemplate_TagSpecification{
			ResourceType: gfnt.NewString("instance"),
			Tags:         cfnTags,
		}, gfnec2.LaunchTemplate_TagSpecification{
			ResourceType: gfnt.NewString("volume"),
			Tags:         cfnTags,
		})

	if injectGpuAndSpotInstancesTags {
		launchTemplateTagSpecs = append(launchTemplateTagSpecs,
			gfnec2.LaunchTemplate_TagSpecification{
				ResourceType: gfnt.NewString("elastic-gpu"),
				Tags:         cfnTags,
			}, gfnec2.LaunchTemplate_TagSpecification{
				ResourceType: gfnt.NewString("spot-instances-request"),
				Tags:         cfnTags,
			})
	}

	return launchTemplateTagSpecs
```

add `injectGpuAndSpotInstancesTags` parameter to `makeTags` function to conditionally inject gpu and spot instance tags into launch template.
```go
func makeTags(ng *api.NodeGroupBase, meta *api.ClusterMeta, injectGpuAndSpotInstancesTags bool) []gfnec2.LaunchTemplate_TagSpecification {
```
> Note: as mentioned in one of commit, currently self-managed nodes fails to launch when launch template is tagged for elastic-gpu and spot instances. However, there is no issue with managed nodes

Merge user defined tags via `--tags` in `AddAllResources()` function in `nodegroup.go`
```go
	if n.spec.Tags == nil {
		n.spec.Tags = map[string]string{}
	}

	for k, v := range n.clusterSpec.Metadata.Tags {
		if _, exists := n.spec.Tags[k]; !exists {
			n.spec.Tags[k] = v
		}
	}
``` 

Add `TagSpecifications` in `newLaunchTemplateData` in `nodegroup.go`

Merge user defined tags into nodespec tags in `AddAllResources` function in `managed_nodegroup.go`
```go
	for k, v := range m.clusterConfig.Metadata.Tags {
		if _, exists := m.nodeGroup.Tags[k]; !exists {
			m.nodeGroup.Tags[k] = v
		}
	}
```

### Checklist
- [x] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [x] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Callisto13** [comment]
Thanks @saleem-mirza 🎉  someone will get to reviewing this asap.

And that PR description is just ❤️ 🚀  love the detail guiding us through your changes!

**Comment by Callisto13** [comment]
@saleem-mirza in your manual testing, were you able to verify that the `spot-instances-request` tag is attached to the managed ng spot request? I just deployed a managed ng with `spot: true` and could not see the tag on the request in the console.

**Comment by saleem-mirza** [comment]
Yes. But for managed nodes only

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by saleem-mirza** [comment]
@Callisto13 ~~Yes. But are managed nodes only~~
I was mistaken. I noticed there is weird behavior that tags for elastic-gpu and spot instances are being ignored for managed nodes while being pushed (visible) for self-managed nodes, however LaunchTemplate fails to launch any instance because of missing resources such as elastic-gpu and/or spot instance.

I have filed a bug report with AWS.

**Comment by Callisto13** [comment]
@saleem-mirza yes i got it was for managed ngs only, but i cannot see the label on the spot request for a managed ng with spot that i created. can you verify that the label is attached to spot requests for managed ngs?

**Comment by Callisto13** [comment]
> elastic-gpu and spot instances are being ignored for managed nodes 

ah so the spot instances request label is not working for managed nodes?

**Comment by saleem-mirza** [comment]
I see tags are being pushed to spot instance itself but not shown in LT -> Resource Tags in AWS dashboard. weird :) but from `eskctl` perspective, it is working.

image

**Comment by saleem-mirza** [comment]
> @saleem-mirza yes i got it was for managed ngs only, but in the console i cannot see the label on the spot request for a managed ng with spot that i created. can you verify in the console that the label is attached to spot requests for managed ngs?

This PR add tags, not labels.

**Comment by Callisto13** [comment]
> This PR add tags, not labels.
oh yeh  i meant tags, typo

**Comment by Callisto13** [comment]
yeh i can see tags on the instance page, do you see anything on the Spots Requests resource page?

**Comment by saleem-mirza** [comment]
no, nothing on request resource page.

**Comment by saleem-mirza** [comment]
Just for record, when pushing `elastic-gpu` and same is applicable for `spot-instance-request` for self-managed group, LT shows following error in Activity tab.

```
Launching a new EC2 instance. Status Reason: 
You cannot specify tags for elastic GPUs if there are no elastic GPUs being created by the request. 
Launching EC2 instance failed.
```
But CloudFormation keep waiting for LT to return (kind of forever), and LT just stuck in trying to create resource. :(

**Comment by Callisto13** [comment]
According to the [docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#tag-new-spot-instance-request) the tag `ResourceType: gfnt.NewString("spot-instances-request"),` should add the tag to the request, unless I have misunderstood it? So i think for eksctl setting `--spot` should have added a tag there.

**Comment by saleem-mirza** [comment]
well, in both cases, nothing in spot request. So there is a broken link somewhere.

**Comment by Callisto13** [comment]
> If tags are present in LT, and not in spot request, then issue is on AWS side.

Yep I agree

> Please correct me if I'm missing anything but this is why we see user defined tags on spot instance itself.

I verified that `ResourceType: gfnt.NewString("spot-instances-request")` tags on the request do not effect the tags on the spot instances (i commented out tagging that resource and built a new managed ng, saw the instance tags were identical to one with the request tagging), so what do you think about removing that resource tagging for now and creating a new issue to tag spot requests (m-ngs) and i can follow up with aws re: CF on my next call with them?

**Comment by saleem-mirza** [comment]
disclaimer: I am with AWS :) and if you have time, I can send you a quick meeting request. Please acknowledge and delete this comment

**Comment by Callisto13** [comment]
😂  probs don't need a call, just was looking to make AWS aware of the gap, sounds like they already are ;)

**Comment by saleem-mirza** [comment]
Since changes related to `spot-instance-request` does not have any impact on functionality of `eksctl` or `eks` itself, I suggest to leave it as it is, unless you suggest otherwise.

I can rollback change.

**Comment by Callisto13** [comment]
👍  yeh i think let's remove the tagging of the spot request resource

**Comment by saleem-mirza** [comment]
yes, it makes sense.

**Review by Callisto13 — APPROVED** [review]

**Pull request merged**
