### PR TITLE
update AWS node to 1.9

### LINKED ISSUE #4037: Update aws-node CNI Version in eksctl utils
**What feature/behavior/change do you want?**
Please, update eksctl to rollout aws-node v1.8.0 or higher. At the moment v1.7.10 will be installed/updated with eksctl utils update-aws-node. 

**Why do you want this feature?**
Problem is that v1.7.10 had a Bug and all of our EKS are affected by this. This bug is fixed in v1.8.0 or newer. 
Maybe it make also sense to add a --version parameter to use a specific version. Good to test new versions.

### PR DESCRIPTION
**Pull request by aclevername**
### Description

Closes #4037 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by Himangini — APPROVED** [review]
LGTM

**Comment by Callisto13** [comment]
@aclevername if you want this released today merge before 11 plz

**Comment by aclevername** [comment]
@Callisto13 @cPu1 I would like to merge, but I don't know enough about this to know if this PR is enough to bump the aws node :joy: this hasn't been touched for a long time. Thoughts?

**Review by cPu1 — APPROVED** [review]

**Comment by aclevername** [comment]
running the `update` suite locally

**Comment by aclevername** [comment]
```
[0] Ran 5 of 5 Specs in 3279.613 seconds
[0] SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
[0] PASS
```

**Pull request merged**
