### PR TITLE
Update aws-node addon

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Closes https://github.com/weaveworks/eksctl/issues/4477

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Skarlso** [comment]
Yaaay

```
k get pods -A
NAMESPACE     NAME                       READY   STATUS    RESTARTS        AGE
kube-system   aws-node-d67g6             1/1     Running   1 (2m42s ago)   4m41s
kube-system   coredns-657694c6f4-72nz2   1/1     Running   0               14m
kube-system   coredns-657694c6f4-8vjnw   1/1     Running   0               14m
kube-system   kube-proxy-lfl2v           1/1     Running   0               4m41s
```

With following config:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gb-test-ipv6-01
  region: us-west-2
  version: '1.22'

kubernetesNetworkConfig:
  ipFamily: IPv6 # or IPv4

addons:
  - name: vpc-cni
    version: 1.11.0
  - name: coredns
  - name: kube-proxy

iam:
  withOIDC: true

managedNodeGroups:
  - name: mng-1
    desiredCapacity: 1

```

**Review by Himangini — COMMENTED** [review]
Quick ques, are we not removing this validation https://github.com/weaveworks/eksctl/commit/5150ae3904e6ac07791ca7015afefb0b234c3d25 as part of this PR?

**Comment by Skarlso** [comment]
> Quick ques, are we not removing this validation [5150ae3](https://github.com/weaveworks/eksctl/commit/5150ae3904e6ac07791ca7015afefb0b234c3d25) as part of this PR?

Good question! I was actually thinking about that and did remove it at first. Then put it back because we still need a minimum version verification I think. At the very least, we need the verification for it being empty or latest. It's a grey area I'm not sure what to do about. :))))

**Comment by Skarlso** [comment]
@Himangini Oh right! So sorry. :D It's because we changed that flow a bit. Now `latest` is discovered and if it isn't the minimum supported then we error : https://github.com/weaveworks/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/validation.go#L281

**Review by Himangini — COMMENTED** [review]
Just wondering why this is labeled `kind/feature`, this should be `kind/improvement` right?

**Review by Himangini — APPROVED** [review]
LGTM 👍🏻

**Review by cPu1 — APPROVED** [review]

**Pull request merged**
