### PR TITLE
Auto format example files for consistency

### PR DESCRIPTION
**Pull request by sayboras**
### Description

Auto format example files for consistency

### Checklist
- [ ] ~~Added tests that cover your change (if possible)~~
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] ~~Manually tested~~
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by sayboras** [comment]
> Hmm might be a good idea to just check `examples/` with `prettier` (or something else? alternatives?) too.

I am relying no auto format code from Goland, but not sure which tool it used. I have tried [prettier](https://prettier.io/docs/en/cli.html) before, however, it didn't align comment well. Any suggestion or recommendation on tool ? Thanks

Goland
image

Prettier 
image

**Comment by michaelbeaumont** [comment]
Hmm I'd prefer something universally available so that everyone can replicate the formatting

**Comment by sayboras** [comment]
> Hmm I'd prefer something universally available so that everyone can replicate the formatting

@michaelbeaumont What could be the right place to add this prettier tool ? We can have the installation step in makefile or just add it in eksctl-build. Either way is not idea in my opinion as it will polute code base (not to mention that it's javascript). 

Another alternative option is to use gihub action for this purpose. However, it might prevent developer to run and check before commit.

**Comment by michaelbeaumont** [comment]
I could imagine a pre-commit hook. Any other tool would be fine, just should be one that can be run by everyone.

**Comment by sayboras** [comment]
Seems like it might take longer to discuss and most likely we will go with different approach compared to changes in this PR.

Close this PR and create one issue for tracking purpose.

**Pull request closed without merging**
