### PR TITLE
Fix integration tests for `get cluster`

### PR DESCRIPTION
**Pull request by cPu1**
### Description

This changelist fixes the integration tests for `get clusters`. The tests were failing because, as of a few releases ago, `eksctl get cluster` logs the version and region, but this wasn't taken into account when the assertions were added. 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by cPu1** [comment]
I'm running the CRUD integration tests locally.

**Comment by nikimanoledaki** [comment]
Hey @cPu1! Did the tests pass locally?

**Comment by cPu1** [comment]
> Hey @cPu1! Did the tests succeed locally?

CRUD passed, waiting for unowned to finish.

**Review by nikimanoledaki — APPROVED** [review]

**Review by Himangini — APPROVED** [review]

**Comment by Himangini** [comment]
🚢

**Pull request merged**
