### PR TITLE
Add Ubuntu 20.04 Image Support

### PR DESCRIPTION
**Pull request by powersj**
### Description

Starting with EKS 1.18, the official Ubuntu EKS images are based on
Ubuntu 20.04 LTS (Focal). EKS 1.17 is the last release to use
Ubuntu 18.04 LTS (Bionic) as a base.

There are two additions here:

* Add CLI support for the Ubuntu2004 family
* Create a new bootstrap script specific to Ubuntu2004

Ubuntu 20.04 EKS images, are no longer disabling the
systemd-resolved's DNS stub listener. Without this, the CoreDNS will
assume there is a loop when trying to incorrectly use
/etc/resolv.conf.

Issue #2757 
 
### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by powersj** [comment]
I built and launched this locally:

```shell
$ ./eksctl version
0.31.0-dev+8bb07a39.2020-10-20T15:08:12Z
```
And launched a test cluster using the new ami family:

```shell
$ ./eksctl create cluster --name eksctl --version 1.18 --nodegroup-name nodes --node-type t3.large --nodes 2 --nodes-min 1 --nodes-max 2 --node-ami ami-0a0d5ab7ab13d62a6 --node-ami-family Ubuntu2004 --region us-west-2 --ssh-access --ssh-public-key powersj
[ℹ]  eksctl version 0.31.0-dev+8bb07a39.2020-10-20T15:08:12Z
[ℹ]  using region us-west-2
[ℹ]  setting availability zones to [us-west-2b us-west-2a us-west-2d]
[ℹ]  subnets for us-west-2b - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for us-west-2a - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for us-west-2d - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "nodes" will use "ami-0a0d5ab7ab13d62a6" [Ubuntu2004/1.18]
[ℹ]  using EC2 key pair %!!(MISSING)q(*string=<nil>)
[ℹ]  using Kubernetes version 1.18
[ℹ]  creating EKS cluster "eksctl" in "us-west-2" region with un-managed nodes
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-west-2 --cluster=eksctl'
[ℹ]  CloudWatch logging will not be enabled for cluster "eksctl" in "us-west-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=us-west-2 --cluster=eksctl'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "eksctl" in "us-west-2"
[ℹ]  2 sequential tasks: { create cluster control plane "eksctl", 2 sequential sub-tasks: { no tasks, create nodegroup "nodes" } }
[ℹ]  building cluster stack "eksctl-eksctl-cluster"
[ℹ]  deploying stack "eksctl-eksctl-cluster"
[ℹ]  building nodegroup stack "eksctl-eksctl-nodegroup-nodes"
[ℹ]  deploying stack "eksctl-eksctl-nodegroup-nodes"
[ℹ]  waiting for the control plane availability...
[✔]  saved kubeconfig as "/home/powersj/.kube/config"
[ℹ]  no tasks
[✔]  all EKS cluster resources for "eksctl" have been created
[ℹ]  adding identity "arn:aws:iam::927445640099:role/eksctl-eksctl-nodegroup-nodes-NodeInstanceRole-1SY96B9JAZCM3" to auth ConfigMap
[ℹ]  nodegroup "nodes" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "nodes"
[ℹ]  nodegroup "nodes" has 2 node(s)
[ℹ]  node "ip-192-168-1-34.us-west-2.compute.internal" is ready
[ℹ]  node "ip-192-168-76-2.us-west-2.compute.internal" is not ready
[ℹ]  kubectl command should work with "/home/powersj/.kube/config", try 'kubectl get nodes'
[✔]  EKS cluster "eksctl" in "us-west-2" region is ready
```

This was sucessful in creating the pods:

```shell
$ kubectl get nodes --watch
NAME                                         STATUS     ROLES    AGE   VERSION
ip-192-168-76-2.us-west-2.compute.internal   NotReady   <none>   0s    v1.18.9
ip-192-168-1-34.us-west-2.compute.internal   NotReady   <none>   0s    v1.18.9
ip-192-168-76-2.us-west-2.compute.internal   NotReady   <none>   0s    v1.18.9
ip-192-168-1-34.us-west-2.compute.internal   NotReady   <none>   0s    v1.18.9
ip-192-168-76-2.us-west-2.compute.internal   NotReady   <none>   0s    v1.18.9
ip-192-168-1-34.us-west-2.compute.internal   NotReady   <none>   0s    v1.18.9
ip-192-168-76-2.us-west-2.compute.internal   NotReady   <none>   30s   v1.18.9
ip-192-168-1-34.us-west-2.compute.internal   NotReady   <none>   30s   v1.18.9
ip-192-168-76-2.us-west-2.compute.internal   NotReady   <none>   60s   v1.18.9
ip-192-168-1-34.us-west-2.compute.internal   Ready      <none>   70s   v1.18.9
ip-192-168-1-34.us-west-2.compute.internal   Ready      <none>   70s   v1.18.9
ip-192-168-76-2.us-west-2.compute.internal   Ready      <none>   80s   v1.18.9
^C
$ kubectl get pods --all-namespaces 
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   aws-node-6zszr             1/1     Running   0          87s
kube-system   aws-node-pdwpg             1/1     Running   0          87s
kube-system   coredns-559b5db75d-gv7zc   1/1     Running   0          8m25s
kube-system   coredns-559b5db75d-xmd4m   1/1     Running   0          8m25s
kube-system   kube-proxy-66g6z           1/1     Running   0          87s
kube-system   kube-proxy-6fwsw           1/1     Running   0          87s
```

**Comment by ilpianista** [comment]
Thanks, I was also affected by this. As workaround, I [customized kubelet](https://eksctl.io/usage/customizing-the-kubelet/) by passing a different `resolv.conf` file to pods:

```
kubeletExtraConfig:
  resolvConf: /run/systemd/resolve/resolv.conf
```

**Comment by michaelbeaumont** [comment]
> Thanks, I was also affected by this. As workaround, I [customized kubelet](https://eksctl.io/usage/customizing-the-kubelet/) by passing a different `resolv.conf` file to pods:
> 
> ```
> kubeletExtraConfig:
>   resolvConf: /run/systemd/resolve/resolv.conf
> ```

Duplicating the entire bootstrap script for one line doesn't feel right, can you inject the setting this way? I.e. in `makeKubeletConfigYAML` @powersj

**Comment by powersj** [comment]
@michaelbeaumont I was looking at doing something like:

```go
	if ng.AMIFamily == api.NodeImageFamilyUbuntu2004 {
		ng.KubeletExtraConfig = &api.InlineDocument{
			"resolvConf": "/run/systemd/resolve/resolv.conf",
		}
	}
```

My lack of go experience is going to come out here, do I need to check if `ng.KubeletExtraConfig` is not nil and if so doing some merging?

**Comment by michaelbeaumont** [comment]
> @michaelbeaumont I was looking at doing something like:
> 
> ```go
> 	if ng.AMIFamily == api.NodeImageFamilyUbuntu2004 {
> 		ng.KubeletExtraConfig = &api.InlineDocument{
> 			"resolvConf": "/run/systemd/resolve/resolv.conf",
> 		}
> 	}
> ```
> 
> My lack of go experience is going to come out here, do I need to check if `ng.KubeletExtraConfig` is not nil and if so doing some merging?

No worries, go for it, I'll review it! I suspect yes you'll need to check `!= nil` (if that's false set to `make(map[string]interface{})`) then just set `"resolvConf"`

**Comment by powersj** [comment]
@michaelbeaumont forced pushed up some new changes:

If launching a NodeImageFamilyUbuntu2004:
1) If KubeletExtraConfig is empty, create the KubeletExtraConfig with the resolvConf
2) If KubeletExtraConfig is not empty, set the KubeletExtraConfig setting, only if the user has not set it as user settings should take priority

**Comment by michaelbeaumont** [comment]
@powersj Hey I hope you don't mind, I pushed a few commits to the PR because I wanted to get it into the RC today.

**Comment by powersj** [comment]
@michaelbeaumont +1 to the changes, thanks for cleaning things up!

**Review by michaelbeaumont — APPROVED** [review]
LGTM :slightly_smiling_face:

**Review by cPu1 — APPROVED** [review]
LGTM. Thanks for the PR @powersj :tada:

**Pull request merged**
