### PR TITLE
Node private networking

### LINKED ISSUE #120: Private Subnets for Worker Nodes
Feature Suggestion: eksctl should favor, or at least offer the option of, creating a VPC for the EKS cluster with private subnets for worker nodes. 

I was surprised to find that the nodes created via eksctl all had internet facing IP addresses assigned to them. Perhaps there is a technical reason for this of which I am unaware, however the EKS documentation seems to encourage the use of a private subnet for worker nodes as seen here: https://docs.aws.amazon.com/eks/latest/userguide/create-public-private-vpc.html

### PR DESCRIPTION
**Pull request by errordeveloper**
### Description

Add `--node-private-networking` flag, which will make initial nodegroup use private subnet.

- close #120 

### Checklist
- [x] Code compiles correctly (i.e `make build`)
- [x] Added tests that cover your change (if possible)
- [x] All tests passing (i.e. `make test`)

### CODE REVIEW

**Comment by errordeveloper** [comment]
cc @mwelch-ptc @shatil

**Comment by mwelch-ptc** [comment]
This is terrific! I look forward to trying it out.

**Comment by errordeveloper** [comment]
It's ready for someone to review, but I'd like to make sure it does what's intended (in theory it should, but I might have missed something).

**Comment by errordeveloper** [comment]
Thanks @stefanprodan!

**Pull request merged**
