### PR TITLE
Add more flexible subnet support, specifying subnets for nodegroup

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Description
See:
https://github.com/weaveworks/eksctl/issues/475#issuecomment-498995479
https://github.com/weaveworks/eksctl/issues/806#issuecomment-501854053

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by aclevername** [comment]
@michaelbeaumont can we get an example manifest added for this?

**Comment by michaelbeaumont** [comment]
> @michaelbeaumont can we get an example manifest added for this?

Done!

**Review by cPu1 — APPROVED** [review]

**Comment by igoratencompass** [comment]
Is this working with Public subnets only? 

I'm launching an EKS cluster in an existing VPC with Public and Private subnets and when I set `nodeGroups.subnets` to a list of Private subnets I get an error saying the subnets do not exist:

```
[✖]  VPC doesn't have subnet with name subnet-xxxxxxxxxxxxxx014 (allSubnets=v1alpha5.AZSubnetMapping{"eu-west-1a":v1alpha5.AZSubnetSpec{ID:"subnet-xxxxxxxxxxxxxx014", AZ:"eu-west-1a", CIDR:(*ipnet.IPNet)(0xc000272db0)}, "eu-west-1b":v1alpha5.AZSubnetSpec{ID:"subnet-xxxxxxxxxxxxxx055", AZ:"eu-west-1b", CIDR:(*ipnet.IPNet)(0xc000272cf0)}, "eu-west-1c":v1alpha5.AZSubnetSpec{ID:"subnet-xxxxxxxxxxxxxx693", AZ:"eu-west-1c", CIDR:(*ipnet.IPNet)(0xc000272d50)}} AZs=[]string(nil) subnets=[]string{"subnet-xxxxxxxxxxxxxx014", "subnet-xxxxxxxxxxxxxx055", "subnet-xxxxxxxxxxxxxx693"})
```

They exist for sure:

```
$ aws ec2 describe-subnets --region=eu-west-1 --filters "Name=vpc-id,Values=vpc-xxxxxxxxxxxxxxa53" \
--query 'Subnets[*].{Subnet_ID:SubnetId,AZ:AvailabilityZone,Name:Tags[?Key==`Name`].Value|[0],Type:Tags[?Key==`SubnetType`].Value|[0]}'
[
    {
        "Subnet_ID": "subnet-xxxxxxxxxxxxxx055", 
        "AZ": "eu-west-1b", 
        "Type": "Private"
    }, 
    {
        "Subnet_ID": "subnet-xxxxxxxxxxxxxx693", 
        "AZ": "eu-west-1c", 
        "Type": "Private"
    }, 
    {
        "Subnet_ID": "subnet-xxxxxxxxxxxxxx014", 
        "AZ": "eu-west-1a", 
        "Type": "Private"
    }
]
```
The relevant part of the cluster YAML:

```
vpc:
  subnets:
    public:
      eu-west-1a:
        id: subnet-xxxxxxxxxxxxxx4d0
      eu-west-1b:
        id: subnet-xxxxxxxxxxxxxx7ac
      eu-west-1c:
        id: subnet-xxxxxxxxxxxxxx906
    private:
      eu-west-1a:
        id: subnet-xxxxxxxxxxxxxx014
      eu-west-1b:
        id: subnet-xxxxxxxxxxxxxx055
      eu-west-1c:
        id: subnet-xxxxxxxxxxxxxx693
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

nodeGroups:
  - name: nodes
    [...]
    privateNetworking: true
    subnets: ["subnet-xxxxxxxxxxxxxx014", "subnet-xxxxxxxxxxxxxx055", "subnet-xxxxxxxxxxxxxx693"]
```

**Comment by michaelbeaumont** [comment]
@igoratencompass the error message is unfortunate here, you need to refer to the subnets by their keys in the subnet map. In your case, `eu-west-1a` etc. You could use the ID as the key.

**Comment by igoratencompass** [comment]
Thanks @michaelbeaumont I'll have that in mind.

**Pull request merged**
