### PR TITLE
Fix typo in asset filename

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Description

This has been bothering me, but it might be a breaking change? @weaveworks/eksctl-reviewers 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [ ] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by Callisto13** [comment]
haha 😂

**Review by cPu1 — APPROVED** [review]

**Comment by michaelbeaumont** [comment]
I'm just worried there may be bootstrap commands in configs that reference the typo filename... `sed ...`, wdyt?

**Comment by Callisto13** [comment]
yeh 😟  we all know that we can put ALLCAPS and all the emoji in the world on the release notes and _still_ somebody will miss it

also I always read `eksclt` as eks cult 🤷‍♀️ .

**Comment by aclevername** [comment]
> I'm just worried there may be bootstrap commands in configs that reference the typo filename... `sed ...`, wdyt?

mhmm thats true, perhaps save this fix for `v1.0.0` when we intend to make breaking changes? We could add a new label for PRs/Issues that we want to fit into `v1.0.0`

**Comment by aclevername** [comment]
Added to `v1.0` proposal https://github.com/weaveworks/eksctl/pull/3047

**Pull request closed without merging**
