### PR TITLE
Add installation instructions for MacPorts on MacOS

### PR DESCRIPTION
**Pull request by szczad**
### Checklist
- [ ] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [ ] Manually tested

### CODE REVIEW

**Comment by martina-if** [comment]
Hi @szczad Thank you for the PR. As you can see, we had to rewrite the history on master to remove a library we had included. Can you please rebase your pr onto the new master?

**Comment by martina-if** [comment]
Hi @szczad , we would like to merge your PR! Can you please rebase it? If you don't have time and you gave us permission to push to your fork we can do it but we prefer if you'd do it to keep you as the only commiter/author.

**Comment by szczad** [comment]
@martina-if Ahhh... Totally forgot about it. I'll have a look at it tomorrow morning. 👌

**Comment by marccarre** [comment]
Superseded by #1708.

**Pull request closed without merging**
