### PR TITLE
Update the link checker

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Checking if non-repo PRs also work with updated checker.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by cPu1 — APPROVED** [review]

**Comment by cPu1** [comment]
Was this accidentally opened? It look like a dupe of #5153.

**Comment by Skarlso** [comment]
@cPu1 That one is on repository branch, this one is on a fork, to test both to be sure. :)

**Comment by cPu1** [comment]
> @cPu1 That one is on repository branch, this one is on a fork, to test both to be sure. :)

Yes, I saw that. I removed my comment.

**Comment by Skarlso** [comment]
Looks like this is also working. Closing this one.

**Pull request closed without merging**
