### PR TITLE
Enable policies for cert-manager.

### PR DESCRIPTION
**Pull request by Yannig**
Fix for https://github.com/weaveworks/eksctl/issues/745

### Checklist

- [X] Code compiles correctly (i.e `make build`)
- [X] Added tests that cover your change (if possible)
- [X] All unit tests passing (i.e. `make test`)
- [ ] All integration tests passing (i.e. `make integration-test`)
- [ ] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [X] Added yourself to the `humans.txt` file

### CODE REVIEW

**Comment by errordeveloper** [comment]
@Yannig thanks very much! This looks good overall, but I wonder if we should make this controlled by a dedicated config field instead of hanging it on `externalDNS` – what do you think?

**Comment by Yannig** [comment]
@errordeveloper no problem. I'm doing it asap.

**Comment by Yannig** [comment]
@errordeveloper what do you think about it?

**Comment by errordeveloper** [comment]
@Yannig thank you, this looks good! Ideally, we would make this a config-only option, if you are okay with that? We have a strong preference to avoid adding new flags, as there are already too many.

**Comment by Yannig** [comment]
I understand. I'm doing the modification.

**Comment by Yannig** [comment]
@errordeveloper I think it's fine now. What do you think about?

**Comment by Yannig** [comment]
Done

**Pull request merged**
