### PR TITLE
Force kubeconfig get-token output format to json

### LINKED ISSUE #6547: [Bug] When the output format of AWS CLI is set to 'table', kubectl will encounter an error when connecting to the EKS created by eksctl
### What were you trying to accomplish?
`eksctl create cluster -f test.yml`

### What happened?
At the end of the EKS creation, the following error is displayed:
```bash
2023-04-20 09:16:38 [✖️]  unable to use kubectl with the EKS cluster (check 'kubectl version'): WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Unable to connect to the server: getting credentials: decoding stdout: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```
kubectl cannot connect to eks.

### How to reproduce it?

set the output to `table` when `aws configure`, and create an eks using eksctl

**Anything else we need to know?**
eksctl should set the output format to `json` in the aws command line when generating `~/.kube/config` instead of relying on the user's AWS profile configuration, which would be a better solution.

### PR DESCRIPTION
**Pull request by yuxiang-zhang**
### Description
Fixes #6547 

AWS CLI introduced a change in https://github.com/aws/aws-cli/pull/7726 as a result of supporting `--output` flag in the `eks get-token` API. We now have to hard-code `--output json` which takes precedence, otherwise the output format will default to [other options](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output-format.html#json-output:~:text=output%20format%20in-,three%20ways,-%3A). Note that the AWS CLI version must be newer than `1.27.86` or `2.11.1`. 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Himangini** [comment]
If the AWS CLI version is lower than `1.27.86` or `2.11.1` does it error when `--output json` is used?

**Comment by yuxiang-zhang** [comment]
> If the AWS CLI version is lower than `1.27.86` or `2.11.1` does it error when `--output json` is used?

No, if it's lower then the `--output` flag will be ignored, but this bug will still be present. Though to me, this isn't an eksctl bug. 

On a related note, have you considered using `aws eks update-kubeconfig` for this? not that it would solve this specific problem, but it does the same thing as `write-kubeconfig`

**Review by Himangini — APPROVED** [review]
👍🏻

**Comment by Himangini** [comment]
> On a related note, have you considered using `aws eks update-kubeconfig` for this? not that it would solve this specific problem, but it does the same thing as `write-kubeconfig`

I haven't. I'll add a note to look into this further at some point. 👍🏻

**Pull request merged**
