### PR TITLE
Changed linter and lint fixes

### PR DESCRIPTION
**Pull request by richardcase**
### Description
Changed the linter from gometalinter to [GolangCI-Lint](
https://github.com/golangci/golangci-lint) as it is faster
and the configuration and output are better.

Fixed issues highlighted by the new linter. The following
linters have been disabled and should be enabled in the future:

- gocyclo
- lll
- gosec

This is further to work already carried out in #206

### Checklist
- [x] Code compiles correctly (i.e `make build`)
- [ ] Added tests that cover your change (if possible)
- [x] All tests passing (i.e. `make test`)
- [ ] Added/modified documentation as required (such as the README)
- [ ] Added yourself to the `humans.txt` file

### CODE REVIEW

**Comment by errordeveloper** [comment]
CI seems unhappy - any ideas? IIRC, we have CGO disabled, so is that why we are getting some CGO weirdness there?

**Comment by richardcase** [comment]
@errordeveloper - yeah i thought from the message it may bbe because CGO is disabbled. I'm going to have a look this morning.

**Comment by errordeveloper** [comment]
We have `CGO_ENABLED=0`, but only when build releases:
```
.goreleaser.yml:      - CGO_ENABLED=0
```

**Comment by errordeveloper** [comment]
I've enabled GolangCI, let's see how it works. But for now, I'd just stick to what we have, I don't think gometalinter is that slow. If we could just make GolangCI do its job, it'd be fine by me to use it along the side with current CircleCI setup.

**Comment by errordeveloper** [comment]
Here is an idea: let's merge this changes, but without enabling new linter in CircleCI =)

**Comment by errordeveloper** [comment]
I like this, now we have some CI redundancy and GolangCI reported before CircleCI jobs finished, because it doesn't run unit tests.

**Comment by richardcase** [comment]
Nice, thats an even better idea

**Pull request merged**
