### PR TITLE
Add deprecation notice to enable repo command

### PR DESCRIPTION
**Pull request by Callisto13**
And also mark all repo codepaths so that removing later is very simple.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by michaelbeaumont — COMMENTED** [review]
Can `MarkDeprecated` also be used here?

https://github.com/weaveworks/eksctl/blob/652052fa5a0abc620a324982e2500e0a7f5a6529/pkg/ctl/update/cluster.go#L36

Or maybe [`cobra.Command.Deprecated/Hidden`](https://github.com/spf13/cobra/blob/1d71ff02701cb01f7e9980754da9c95cb92252d2/command.go#L84-L88)?

**Comment by Callisto13** [comment]
oh dip! totally did not look for pre-existing things 😂

**Comment by Callisto13** [comment]
`fs.MarkDeprecated` wont work for this, because that wraps flags and we are removing a whole subcommand here.  `cobra.Command.Deprecated/Hidden` does work but changes the UX in a way that I think is less clear.

Showing update cluster as an example:

```sh
# current, with our own deprecation note
$ eksctl update cluster --help
DEPRECATED: use 'upgrade cluster' instead. Upgrade control plane to the next Kubernetes version if available. Will also perform any updates needed in the cluster stack if resources are missing.
...

# using cobra command
$ ./eksctl update cluster --help
Command "cluster" is deprecated, use 'upgrade cluster' instead.
Upgrade control plane to the next Kubernetes version if available. Will also perform any updates needed in the cluster stack if resources are missing.
...
```

Cobra supplies the `Command "cluster" is deprecated` at the start, and personally I like the big caps which are easier to spot. WDYT?

**Comment by michaelbeaumont** [comment]
You're right, caps and first word is better!

**Review by michaelbeaumont — APPROVED** [review]

**Pull request merged**
