### PR TITLE
[docs] Fix SSH usage in example

### PR DESCRIPTION
**Pull request by cPu1**
### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [x] All unit tests passing (i.e. `make test`)
- [x] Added/modified documentation as required (such as the `README.md`, and `examples` directory)

### CODE REVIEW

**Comment by errordeveloper** [comment]
@cPu1 do you want to sync docs branch with master or wait for the release?

**Comment by cPu1** [comment]
@errordeveloper let's sync the docs branch now.

**Comment by cPu1** [comment]
Pushed, the site has been updated: https://eksctl.io/examples/reusing-iam-and-vpc/

**Comment by errordeveloper** [comment]
Thank you!

**Pull request merged**
