### PR TITLE
Add RoleARN to NodeGroupSummary

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
### Description

Add possibility to get Instance Role ARN from `eksctl get nodegroup` on YAML and JSON outputs.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [x] Manually tested

### CODE REVIEW

**Comment by t0rr3sp3dr0** [comment]
@errordeveloper, do I have to do anything else to get this pull request merged into master?

**Comment by t0rr3sp3dr0** [comment]
@martina-if could you review this pull request?

**Comment by martina-if** [comment]
Hi @t0rr3sp3dr0 , Thanks for your contribution! Adding the instance role makes sense but the instance profile is not something I've seen requested that much. You could also get it by knowing the instance role. Can you remove that part? 

By the way, we also have this issue if you are interested: https://github.com/weaveworks/eksctl/issues/585 From there eksctl could expose more details from the stacks and in a more organized way.

**Comment by t0rr3sp3dr0** [comment]
@martina-if I've removed instance profile from the code and its tests.

About the issue you mentioned, I'll take a look on that!

**Pull request merged**
