### PR TITLE
Support for attaching existing roles to service accounts

### LINKED ISSUE #2351: Create service account using existing role.
**Why do you want this feature?**
eksctl support IAM roles for service accounts.(IRSA). 
This feature create new IAM role and attach policy.  
So we should manage IAM role by eksctl.  
https://eksctl.io/usage/iamserviceaccounts/

But some user (including me) uses other manage tools like terraform, AWS CDK, ....
And these tools can use other resource's ARN as a variable, so very easy and hard to make a mistake.
So I want to manage IAM role by other tools.
(But I want to manage service account by eksctl :) )

**What feature/behavior/change do you want?**
I would like to propose a feature to create a service account by using an existing IAM Role.
We can manage role and policy by terraform or other tools (AWS CDK) using this feature.

And we can update role's policy  (eksctl doesn't support update IAM policy)

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Description
Fixes #2351 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [ ] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by ryphon** [comment]
@michaelbeaumont do you need any help with this pr? This would _GREATLY_ help me with some things I'm trying to do now due to some restrictive permissions in the space I'm working in.

**Comment by michaelbeaumont** [comment]
@ryphon You're welcome to finish it! Can you specify exactly what the feature you need would look like? Example configs would be great.

**Comment by ryphon** [comment]
`
iam:
  serviceAccounts:
    - attachPolicyARNs:
        - arn:aws:iam::REDACT:policy/eks/eks-oasis-alb-ingress-policy
      metadata:
        name: alb-ingress-controller
        namespace: kube-system
      permissionsBoundary: arn:aws:iam::REDACT:policy/service-centric-permissions-boundary-policy
      tags:
        Component: eks-test
  serviceRolePermissionsBoundary: arn:aws:iam::REDACT:policy/service-centric-permissions-boundary-policy
  withOIDC: true
`

Exactly what the Issue states. I'd like to be able to set up a service account and just attach the Role rather than attaching a policy and letting eksctl create the role. Specifically so I can set the 'path' of the role to be something that I set via the Terraform that creates the rest. I'll start messing with the pr this week, see if I can get the dev environment ready to go and testing properly.

**Comment by michaelbeaumont** [comment]
@ryphon Do you still plan on implementing this?

**Comment by aclevername** [comment]
@michaelbeaumont shall we move this back into the ready for work column?

**Comment by michaelbeaumont** [comment]
Sure

**Pull request closed without merging**
