### PR TITLE
Fix AWS IAM Auth dependency

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Closes https://github.com/weaveworks/eksctl/issues/5140

CI run: https://github.com/weaveworks/eksctl-ci/actions/runs/2462489915

~~_edit_: Gitops still failed. Weird.~~

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Skarlso** [comment]
A new ci run https://github.com/weaveworks/eksctl-ci/actions/runs/2466527346 with fixed container version.

**Comment by Skarlso** [comment]
A new ci run https://github.com/weaveworks/eksctl-ci/actions/runs/2466527346 with fixed container version.

**Comment by Skarlso** [comment]
The single test failure isn't related.

**Review by nikimanoledaki — APPROVED** [review]

**Review by Himangini — APPROVED** [review]
👍🏻

**Comment by Skarlso** [comment]
Going to hold off on merging after the release. :)

**Pull request merged**
