### PR TITLE
Refactor cfn template tests

### PR DESCRIPTION
**Pull request by Callisto13**
### Description

Quite a big diff, but no code is new (I did rearrange some stuff, but that's it).

This is simply a test refactor. It may not be perfect (I got quite tired towards the end and I held off tackling everything as I didn't want to make the diff even bigger), but hopefully it makes this little piece a bit better and easier to add tests to.

These tests are still not great, and that is in part due to the way the package is designed which leads to various things being all tangled up.

Good things:
- More test coverage
- Can now actually focus tests in here
- Easier to add to (I hope)
- My vim does not crash!

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [x] Backfilled missing tests for code in same general area :tada:
- [x] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Callisto13** [comment]
reminder: add tests for https://github.com/weaveworks/eksctl/pull/3518 now that it is easier to do so

**Review by aclevername — APPROVED** [review]

**Comment by Callisto13** [comment]
i don't believe for a second that you read any of that @aclevername

**Comment by aclevername** [comment]
> i don't believe for a second that you read any of that @aclevername

I read all the `It("..` and `Context("..` and was happy enough.

**Comment by Callisto13** [comment]
hmmm i'll allow it

**Review by cPu1 — APPROVED** [review]

**Pull request merged**
