### PR TITLE
Fix linux eksctl path

### PR DESCRIPTION
**Pull request by BrionStone**
### Description

Updated linux path to current directory hierarchy given in AWS EKS docs.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `site/content` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [ ] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by martina-if** [comment]
Hi @BrionStone , thank you for contributing to eksctl.

I just deprecated that url via https://github.com/weaveworks/eksctl/commit/7b17481d1c4c56525b83cf1053cb2fcbff3057e3

Can you please point me to where you found the old link so I can update that too?

**Comment by BrionStone** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html has the 'latest_release' path, instead of the 'latest' path in your README.md.

**Comment by martina-if** [comment]
Thanks a lot @BrionStone for the link. Also this made me realized that I had put the wrong URLs. I opened a PR to fix the AWS docs 
https://github.com/awsdocs/amazon-eks-user-guide/pull/94
And one for fixing our URLS: 
https://github.com/weaveworks/eksctl/pull/1858

But if you want to make the same cahnges of #1858 here I can close my PR and merge this one :)

**Comment by martina-if** [comment]
Fixed via #1858 instead

**Comment by BrionStone** [comment]
No worries, @martina-if.  I just wanted to go beyond the typical "fix this old/broken link".  Glad you got to a working solution!

**Pull request closed without merging**
