### PR TITLE
Return an error when container runtime and overrideBootstrapCommand are defined together

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Closes https://github.com/weaveworks/eksctl/issues/5363

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by cPu1 — APPROVED** [review]

**Review by Himangini — COMMENTED** [review]
Can you add the output of manual test run?

Small nit for the title to go in release notes : 
`Return an error in case container runtime and overrideBootstrapCommand is defined` should be  
`Return an error when container runtime and overrideBootstrapCommand are defined together`

**Comment by Skarlso** [comment]
Manual run:

```
eksctl create cluster -f cluster-managed.yaml
Error: overrideBootstrapCommand overwrites container runtime setting; please use --container-runtime in the boostrap script instead
```

config:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gb-test-cluster-2
  region: us-west-2
  version: '1.22'

nodeGroups:
  - name: managed-ng-1
    ami: ami-12345
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 4
    desiredCapacity: 1
    containerRuntime: containerd
    overrideBootstrapCommand: |
      #!/bin/bash

      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh

      # Note "--node-labels=${NODE_LABELS}" needs the above helper sourced to work, otherwise will have to be defined manually.
      /etc/eks/bootstrap.sh test-override-11 --container-runtime containerd --kubelet-extra-args "--node-labels=${NODE_LABELS}"

```

**Comment by steffakasid** [comment]
Little correction it seems it throws the error when using the `eksctl scale nodegroup` command creation of nodegroups `eksctl create nodegroup` works fine. Should I create an issue for that?

**Comment by Skarlso** [comment]
Hello @steffakasid!

Yes, please! Thank you! :)

**Pull request merged**
