### PR TITLE
Docs: add requirement for aws-iam-authenticator

### PR DESCRIPTION
**Pull request by bboreham**
### Description

Mention that the tool `aws-iam-authenticator` tool is needed, in the basic installation instructions.

I hit the error message described at #209, and since #211 was never finished I couldn't see any hints what to do.

The text in this PR is adapted from #211.

### CODE REVIEW

**Comment by 2opremio** [comment]
I also experienced this problem on my first use

**Comment by errordeveloper** [comment]
LGTM, but I am sure this was documented previously, could we double-check please?

**Comment by bboreham** [comment]
Check away: https://github.com/weaveworks/eksctl/search?l=Markdown&q=aws-iam-authenticator

**Comment by errordeveloper** [comment]
@bboreham I see, so we only say:

> If you have `kubectl` v1.10.x as well as `aws-iam-authenticator` commands in your PATH, you should be
able to use `kubectl`.

Which is very much buried right now... it probably used to be sufficient when the docs had much less to say.

**Pull request merged**
