### PR TITLE
Native Bottlerocket support in managed nodegroups

### LINKED ISSUE #4211: Native support for Bottlerocket in managed nodegroups
Today, eksctl supports Bottlerocket in managed nodegroups by supplying a custom bootstrap script to the launch template passed to the API. EKS is going to support Bottlerocket natively, eliminating the need to supply a custom bootstrap script. This will not be a user-visible change as the UX for creating Bottlerocket managed nodegroups will remain unchanged. 

More info: https://github.com/aws/containers-roadmap/issues/950

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Closes #4211 

### Checklist
- [x] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by rothgar** [comment]
Are there instructions on how I can use this feature? I tried this binary with

```
eksctl create cluster testing --managed --node-ami-family bottlerocket
```

but get the error

```
Error: "bottlerocket" is not supported for managed nodegroups
```

**Comment by Skarlso** [comment]
@rothgar Which version did you try? It might not have been officially released yet.

**Comment by rothgar** [comment]
I tried the RC release 
image

**Comment by rothgar** [comment]
I just tried with the full .72 release too (although I know it didn't have any changes)

image

It **does** work with a configuration file with bottlerocket. Just not at the CLI. I used this and got a working cluster.

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket
  region: us-east-2

managedNodeGroups:
  - name: ng-bottlerocket
    desiredCapacity: 3
    amiFamily: Bottlerocket
```

**Comment by cPu1** [comment]
> I just tried with the full .72 release too (although I know it didn't have any changes)
> 
> image
> 
> It **does** work with a configuration file with bottlerocket. Just not at the CLI. I used this and got a working cluster.
> 
> ```
> ---
> apiVersion: eksctl.io/v1alpha5
> kind: ClusterConfig
> 
> metadata:
>   name: bottlerocket
>   region: us-east-2
> 
> managedNodeGroups:
>   - name: ng-bottlerocket
>     desiredCapacity: 3
>     amiFamily: Bottlerocket
> ```

Hi @rothgar, the value for `--node-ami-family` is case sensitive. The command should be
```shell
$ eksctl create cluster -n bottlerock --node-ami-family Bottlerocket
```

**Comment by rothgar** [comment]
Thanks! I must have missed that :facepalm: It's working now.

Would it be possible to make that case insensitive? I'm not sure if you're searching the SSM parameters or doing a direct search for the latest AMI. I _thought_ the aws cli search was case insensitive but I could be wrong.

**Comment by akestner** [comment]
+1 on making this case insensitive

**Comment by cPu1** [comment]
@rothgar eksctl uses Kubernetes-style UpperCamelCase (or Pascal case) values for enums like Bottlerocket, AmazonLinux2 etc., and does not rely on the case of the AMI family to query the SSM parameter store. I agree that the UX for the issue you encountered can be improved and have opened an issue with details: https://github.com/weaveworks/eksctl/issues/4439.

**Pull request merged**
