### PR TITLE
Fix iamserviceaccount `create` duplicate entry check not being behind the created flag

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Fix the crud duplication test failure by only checking duplication if the flag is on.

Introduced in this pr: https://github.com/weaveworks/eksctl/pull/4963/

Closes https://github.com/weaveworks/eksctl/issues/5081

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by Himangini — COMMENTED** [review]
Q: is this needs a` skip-release-notes` label? If not then can we add a good title description that goes in release notes :)

**Comment by Skarlso** [comment]
@Himangini Yeah, I was thinking about that too! I think you're right. I should create a bug for this. :)

**Comment by Skarlso** [comment]
Added an issue and title. :)

**Comment by Skarlso** [comment]
I will run a crud test for this tomorrow.

**Review by aclevername — APPROVED** [review]

**Comment by aclevername** [comment]
> @Himangini Yeah, I was thinking about that too! I think you're right. I should create a bug for this. :)

do we need a bug report for an unreleased feature? I don't think it needs to be mentioned in the release notes since its fixing a bug that never existed 😁

**Pull request merged**
