### PR TITLE
Use the latest neuron-device-plugin

### LINKED ISSUE #2955: Use the latest neuron device plugin
**What happened?**
When eksctl is used to create a cluster with inf1 devices and if the latest neuron-sdk is running on container, they don't come up.

**What you expected to happen?**
eksctl is getting a old version of neuron device pluging

**How to reproduce it?**
Create a eks cluster using following command
```
eksctl create nodegroup \                                                                                                         
    --cluster eks-inf1-demo-cluster \                                                                                             
    --region us-west-2 \                                                                                                          
    --name ng-inf1-xlarge \                                                                                                       
    --node-type inf1.xlarge \                                                                                                     
    --nodes 1 \                                                                                                                   
    --nodes-min 1 \                                                                                                               
    --nodes-max 1 \                                                                                                               
    --ssh-access
```
The create a application container using instructions from below
https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/tensorflow/k8s_bert_demo/README.md

The application container will not come up.

**Versions**
```
$ eksctl version
0.34.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by aws-vrnatham**
Signed-off-by: Venky Natham <vrnatham@amazon.com>

### Description

Fixes #2955

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [ ] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Review by aclevername — APPROVED** [review]
Thanks for the PR @aws-vrnatham ! LGTM. You need to update the auto-generated files before being able to merge. You can do that by running `make generate-all` . 

 For my future self heres where the release notes live: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-k8.html

**Comment by micwade-aws** [comment]
The change requested by @aclevername needs to be addressed, but the device plugin version can be updated to 1.3.0. 

Until this gets merged (with it without the change to 1.3), the Inf1 demos that use eksctl are broken.

**Comment by aws-vrnatham** [comment]
> Thanks for the PR @aws-vrnatham ! LGTM. You need to update the auto-generated files before being able to merge. You can do that by running `make generate-all` .
> 
> For my future self heres where the release notes live: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-k8.html

I am seeing the following when I run make generate-all

ubuntu@ip-10-1-200-237:~/go/src/eksctl$ make generate-all
flag provided but not defined: -v
Usage: go-bindata [options] <input directories>

  -debug
        Do not embed the assets, but provide the embedding API. Contents will still be loaded from disk.
  -dev
        Similar to debug, but does not emit absolute paths. Expects a rootDir variable to already exist in the generated code's package.
  -fs
        Whether generate instance http.FileSystem interface code.
  -ignore value
        Regex pattern to ignore
  -mode uint
        Optional file mode override for all files.
  -modtime int
        Optional modification unix timestamp override for all files.
  -nocompress
        Assets will *not* be GZIP compressed when this flag is specified.
  -nomemcopy
        Use a .rodata hack to get rid of unnecessary memcopies. Refer to the documentation to see what implications this carries.
  -nometadata
        Assets will not preserve size, mode, and modtime info.
  -o string
        Optional name of the output file to be generated. (default "./bindata.go")
  -pkg string
        Package name to use in the generated code. (default "main")
  -prefix string
        Optional path prefix to strip off asset names.
  -tags string
        Optional set of build tags to include.
  -version
        Displays version information.
Makefile:160: recipe for target 'generate-always' failed
make: *** [generate-always] Error 2

**Comment by aclevername** [comment]
> > Thanks for the PR @aws-vrnatham ! LGTM. You need to update the auto-generated files before being able to merge. You can do that by running `make generate-all` .
> > For my future self heres where the release notes live: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-k8.html
> 
> I am seeing the following when I run make generate-all
> 
> ubuntu@ip-10-1-200-237:~/go/src/eksctl$ make generate-all
> flag provided but not defined: -v
> Usage: go-bindata [options]
> 
> -debug
> Do not embed the assets, but provide the embedding API. Contents will still be loaded from disk.
> -dev
> Similar to debug, but does not emit absolute paths. Expects a rootDir variable to already exist in the generated code's package.
> -fs
> Whether generate instance http.FileSystem interface code.
> -ignore value
> Regex pattern to ignore
> -mode uint
> Optional file mode override for all files.
> -modtime int
> Optional modification unix timestamp override for all files.
> -nocompress
> Assets will _not_ be GZIP compressed when this flag is specified.
> -nomemcopy
> Use a .rodata hack to get rid of unnecessary memcopies. Refer to the documentation to see what implications this carries.
> -nometadata
> Assets will not preserve size, mode, and modtime info.
> -o string
> Optional name of the output file to be generated. (default "./bindata.go")
> -pkg string
> Package name to use in the generated code. (default "main")
> -prefix string
> Optional path prefix to strip off asset names.
> -tags string
> Optional set of build tags to include.
> -version
> Displays version information.
> Makefile:160: recipe for target 'generate-always' failed
> make: *** [generate-always] Error 2

Interesting, I haven't seen that error before. If I had to guess it might be that you have an older version of `go-bindata`. Can you try running `make install-build-deps` first?
https://github.com/weaveworks/eksctl/blob/master/CONTRIBUTING.md#building-eksctl

**Comment by aws-vrnatham** [comment]
> > > Thanks for the PR @aws-vrnatham ! LGTM. You need to update the auto-generated files before being able to merge. You can do that by running `make generate-all` .
> > > For my future self heres where the release notes live: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-k8.html
> > 
> > 
> > I am seeing the following when I run make generate-all
> > ubuntu@ip-10-1-200-237:~/go/src/eksctl$ make generate-all
> > flag provided but not defined: -v
> > Usage: go-bindata [options]
> > -debug
> > Do not embed the assets, but provide the embedding API. Contents will still be loaded from disk.
> > -dev
> > Similar to debug, but does not emit absolute paths. Expects a rootDir variable to already exist in the generated code's package.
> > -fs
> > Whether generate instance http.FileSystem interface code.
> > -ignore value
> > Regex pattern to ignore
> > -mode uint
> > Optional file mode override for all files.
> > -modtime int
> > Optional modification unix timestamp override for all files.
> > -nocompress
> > Assets will _not_ be GZIP compressed when this flag is specified.
> > -nomemcopy
> > Use a .rodata hack to get rid of unnecessary memcopies. Refer to the documentation to see what implications this carries.
> > -nometadata
> > Assets will not preserve size, mode, and modtime info.
> > -o string
> > Optional name of the output file to be generated. (default "./bindata.go")
> > -pkg string
> > Package name to use in the generated code. (default "main")
> > -prefix string
> > Optional path prefix to strip off asset names.
> > -tags string
> > Optional set of build tags to include.
> > -version
> > Displays version information.
> > Makefile:160: recipe for target 'generate-always' failed
> > make: *** [generate-always] Error 2
> 
> Interesting, I haven't seen that error before. If I had to guess it might be that you have an older version of `go-bindata`. Can you try running `make install-build-deps` first? I have `go-bindata version 3.22.0` installed
> https://github.com/weaveworks/eksctl/blob/master/CONTRIBUTING.md#building-eksctl

Thanks. I was able to get make generate-all work fine and have updated the PR.

**Review by cPu1 — APPROVED** [review]

**Review by aclevername — APPROVED** [review]

**Pull request merged**
